// Code generated by mini-go-dev compiler-binary; DO NOT EDIT.
package source

import (
	"github.com/d7z-team/mini-go/compiler/identity"
)

// EncodeIdentityPosition writes the compiler identity schema fields.
func EncodeIdentityPosition(w *identity.Writer, value Position) {
	if !w.EnterStructure() {
		return
	}
	w.String(string(value.File))
	w.Uint(uint64(value.Offset))
	w.Uint(uint64(value.Line))
	w.Uint(uint64(value.Column))
	w.LeaveStructure()
}

// EncodeIdentitySpan writes the compiler identity schema fields.
func EncodeIdentitySpan(w *identity.Writer, value Span) {
	if !w.EnterStructure() {
		return
	}
	EncodeIdentityPosition(w, value.Start)
	EncodeIdentityPosition(w, value.End)
	w.LeaveStructure()
}
