// Code generated by mini-go-dev compiler-binary; DO NOT EDIT.
package semantic

import (
	"github.com/d7z-team/mini-go/compiler/identity"
)

// EncodeIdentityDependencyExport writes the compiler identity schema fields.
func EncodeIdentityDependencyExport(w *identity.Writer, value DependencyExport) {
	if !w.EnterStructure() {
		return
	}
	w.String(string(value.ModulePath))
	w.String(string(value.Name))
	w.String(string(value.ID))
	w.Uint(uint64(value.Kind))
	w.String(string(value.Type))
	w.String(string(value.Underlying))
	w.JSON(value.Value)
	w.Bool(value.Fields != nil)
	w.Uint(uint64(len(value.Fields)))
	for i0 := range value.Fields {
		EncodeIdentityDependencyTypeField(w, value.Fields[i0])
	}
	w.Bool(value.Methods != nil)
	w.Uint(uint64(len(value.Methods)))
	for i0 := range value.Methods {
		EncodeIdentityDependencyTypeMethod(w, value.Methods[i0])
	}
	w.Bool(bool(value.Variadic))
	w.Bool(bool(value.Untyped))
	w.Bool(value.TypeParams != nil)
	w.Uint(uint64(len(value.TypeParams)))
	for i0 := range value.TypeParams {
		w.String(string(value.TypeParams[i0]))
	}
	w.LeaveStructure()
}

// EncodeIdentityDependencyPackage writes the compiler identity schema fields.
func EncodeIdentityDependencyPackage(w *identity.Writer, value DependencyPackage) {
	if !w.EnterStructure() {
		return
	}
	w.String(string(value.ModulePath))
	w.Bool(value.Members != nil)
	w.Uint(uint64(len(value.Members)))
	for i0 := range value.Members {
		EncodeIdentityDependencyExport(w, value.Members[i0])
	}
	w.LeaveStructure()
}

// EncodeIdentityDependencyTypeField writes the compiler identity schema fields.
func EncodeIdentityDependencyTypeField(w *identity.Writer, value DependencyTypeField) {
	if !w.EnterStructure() {
		return
	}
	w.String(string(value.Name))
	w.String(string(value.Type))
	w.Bool(bool(value.Variadic))
	w.String(string(value.Tag))
	w.Bool(bool(value.Embedded))
	w.LeaveStructure()
}

// EncodeIdentityDependencyTypeMethod writes the compiler identity schema fields.
func EncodeIdentityDependencyTypeMethod(w *identity.Writer, value DependencyTypeMethod) {
	if !w.EnterStructure() {
		return
	}
	w.String(string(value.Name))
	w.String(string(value.Receiver))
	w.String(string(value.Signature))
	w.Bool(bool(value.Variadic))
	w.String(string(value.FunctionID))
	w.String(string(value.ModulePath))
	w.LeaveStructure()
}
