// Code generated by mini-go-dev compiler-binary; DO NOT EDIT.
package types

import (
	"github.com/d7z-team/mini-go/compiler/identity"
)

// EncodeIdentityField writes the compiler identity schema fields.
func EncodeIdentityField(w *identity.Writer, value Field) {
	if !w.EnterStructure() {
		return
	}
	w.String(string(value.Name))
	EncodeIdentityTypeRef(w, value.Type)
	w.String(string(value.Tag))
	w.Bool(bool(value.Embedded))
	w.LeaveStructure()
}

// EncodeIdentityFunctionSignature writes the compiler identity schema fields.
func EncodeIdentityFunctionSignature(w *identity.Writer, value FunctionSignature) {
	if !w.EnterStructure() {
		return
	}
	w.Uint(uint64(len(value.Params)))
	for i0 := range value.Params {
		EncodeIdentityTypeParam(w, value.Params[i0])
	}
	w.Uint(uint64(len(value.Results)))
	for i0 := range value.Results {
		EncodeIdentityTypeRef(w, value.Results[i0])
	}
	w.Bool(bool(value.Variadic))
	w.LeaveStructure()
}

// EncodeIdentityMethod writes the compiler identity schema fields.
func EncodeIdentityMethod(w *identity.Writer, value Method) {
	if !w.EnterStructure() {
		return
	}
	w.String(string(value.Name))
	EncodeIdentityTypeRef(w, value.Receiver)
	EncodeIdentityFunctionSignature(w, value.Signature)
	w.String(string(value.FunctionID))
	w.String(string(value.ModulePath))
	w.LeaveStructure()
}

// EncodeIdentityTypeKey writes the compiler identity schema fields.
func EncodeIdentityTypeKey(w *identity.Writer, value TypeKey) {
	if !w.EnterStructure() {
		return
	}
	w.String(string(value.ModulePath))
	w.String(string(value.DeclID))
	w.LeaveStructure()
}

// EncodeIdentityTypeNode writes the compiler identity schema fields.
func EncodeIdentityTypeNode(w *identity.Writer, value TypeNode) {
	if !w.EnterStructure() {
		return
	}
	w.String(string(value.ID))
	w.Uint(uint64(value.Kind))
	w.String(string(value.Name))
	w.Uint(uint64(value.Primitive))
	EncodeIdentityTypeKey(w, value.Identity)
	w.Bool(bool(value.Alias))
	EncodeIdentityTypeRef(w, value.AliasTarget)
	EncodeIdentityTypeRef(w, value.Underlying)
	EncodeIdentityTypeRef(w, value.Elem)
	EncodeIdentityTypeRef(w, value.Key)
	w.Uint(uint64(value.Length))
	w.Uint(uint64(value.Direction))
	w.Bool(value.Signature != nil)
	if value.Signature != nil {
		EncodeIdentityFunctionSignature(w, (*value.Signature))
	}
	w.Uint(uint64(len(value.Tuple)))
	for i0 := range value.Tuple {
		EncodeIdentityTypeRef(w, value.Tuple[i0])
	}
	w.Uint(uint64(len(value.Fields)))
	for i0 := range value.Fields {
		EncodeIdentityField(w, value.Fields[i0])
	}
	w.Uint(uint64(len(value.Methods)))
	for i0 := range value.Methods {
		EncodeIdentityMethod(w, value.Methods[i0])
	}
	w.Uint(uint64(len(value.Terms)))
	for i0 := range value.Terms {
		EncodeIdentityTypeTerm(w, value.Terms[i0])
	}
	w.Bool(bool(value.TypeSet))
	EncodeIdentityTypeRef(w, value.Constraint)
	EncodeIdentityTypeRef(w, value.Base)
	w.Uint(uint64(len(value.TypeArgs)))
	for i0 := range value.TypeArgs {
		EncodeIdentityTypeRef(w, value.TypeArgs[i0])
	}
	w.LeaveStructure()
}

// EncodeIdentityTypeParam writes the compiler identity schema fields.
func EncodeIdentityTypeParam(w *identity.Writer, value TypeParam) {
	if !w.EnterStructure() {
		return
	}
	EncodeIdentityTypeRef(w, value.Type)
	w.LeaveStructure()
}

// EncodeIdentityTypeRef writes the compiler identity schema fields.
func EncodeIdentityTypeRef(w *identity.Writer, value TypeRef) {
	if !w.EnterStructure() {
		return
	}
	w.Uint(uint64(value.Kind))
	w.Uint(uint64(value.Primitive))
	EncodeIdentityTypeKey(w, value.Named)
	w.String(string(value.Node))
	w.LeaveStructure()
}

// EncodeIdentityTypeTable writes the compiler identity schema fields.
func EncodeIdentityTypeTable(w *identity.Writer, value TypeTable) {
	if !w.EnterStructure() {
		return
	}
	w.Uint(uint64(len(value.Nodes)))
	for i0 := range value.Nodes {
		EncodeIdentityTypeNode(w, value.Nodes[i0])
	}
	w.LeaveStructure()
}

// EncodeIdentityTypeTerm writes the compiler identity schema fields.
func EncodeIdentityTypeTerm(w *identity.Writer, value TypeTerm) {
	if !w.EnterStructure() {
		return
	}
	EncodeIdentityTypeRef(w, value.Type)
	w.Bool(bool(value.Approx))
	w.Bool(bool(value.Union))
	w.LeaveStructure()
}
