// Code generated by mini-go-dev compiler-binary; DO NOT EDIT.
package cache

import (
	compiler_ast "github.com/d7z-team/mini-go/compiler/ast"
	"github.com/d7z-team/mini-go/compiler/identity"
	compiler_source "github.com/d7z-team/mini-go/compiler/source"
	compiler_target "github.com/d7z-team/mini-go/compiler/target"
	compiler_types "github.com/d7z-team/mini-go/compiler/types"
	runtime_bytecode "github.com/d7z-team/mini-go/runtime/bytecode"
)

// EncodeIdentityAction writes the compiler identity schema fields.
func EncodeIdentityAction(w *identity.Writer, value Action) {
	if !w.EnterStructure() {
		return
	}
	w.String(string(value.LimitsHash))
	w.String(string(value.Format))
	w.Uint(uint64(value.Version))
	w.String(string(value.Compiler))
	w.String(string(value.IRFormat))
	w.Uint(uint64(value.IRVersion))
	w.String(string(value.OpcodeSet))
	w.String(string(value.IntrinsicSchema))
	w.Uint(uint64(value.Optimization))
	compiler_target.EncodeIdentityTarget(w, value.Target)
	w.String(string(value.PackageID))
	w.String(string(value.ModulePath))
	w.String(string(value.Package))
	w.Uint(uint64(len(value.SourceFiles)))
	for i0 := range value.SourceFiles {
		EncodeIdentitySourceFile(w, value.SourceFiles[i0])
	}
	w.Uint(uint64(len(value.ResourceFiles)))
	for i0 := range value.ResourceFiles {
		EncodeIdentitySourceFile(w, value.ResourceFiles[i0])
	}
	w.Uint(uint64(len(value.DependencyHashes)))
	for i0 := range value.DependencyHashes {
		EncodeIdentityDependency(w, value.DependencyHashes[i0])
	}
	w.LeaveStructure()
}

// EncodeIdentityDependency writes the compiler identity schema fields.
func EncodeIdentityDependency(w *identity.Writer, value Dependency) {
	if !w.EnterStructure() {
		return
	}
	w.String(string(value.ModulePath))
	w.String(string(value.ExportHash))
	w.LeaveStructure()
}

// EncodeIdentityEntryPoint writes the compiler identity schema fields.
func EncodeIdentityEntryPoint(w *identity.Writer, value EntryPoint) {
	if !w.EnterStructure() {
		return
	}
	w.String(string(value.Name))
	w.String(string(value.ModulePath))
	w.String(string(value.Function))
	w.LeaveStructure()
}

// EncodeIdentityGenericExpression writes the compiler identity schema fields.
func EncodeIdentityGenericExpression(w *identity.Writer, value GenericExpression) {
	if !w.EnterStructure() {
		return
	}
	w.Uint(uint64(value.Node))
	compiler_types.EncodeIdentityTypeRef(w, value.Type)
	w.LeaveStructure()
}

// EncodeIdentityGenericReference writes the compiler identity schema fields.
func EncodeIdentityGenericReference(w *identity.Writer, value GenericReference) {
	if !w.EnterStructure() {
		return
	}
	w.Uint(uint64(value.Node))
	w.String(string(value.Name))
	w.String(string(value.ModulePath))
	compiler_source.EncodeIdentitySpan(w, value.Span)
	w.Uint(uint64(value.Kind))
	w.Bool(bool(value.Generic))
	w.String(string(value.Type))
	w.String(string(value.Value))
	w.String(string(value.Imaginary))
	w.Bool(bool(value.Untyped))
	w.LeaveStructure()
}

// EncodeIdentityGenericTemplate writes the compiler identity schema fields.
func EncodeIdentityGenericTemplate(w *identity.Writer, value GenericTemplate) {
	if !w.EnterStructure() {
		return
	}
	w.String(string(value.DeclID))
	w.String(string(value.Kind))
	w.String(string(value.Name))
	w.String(string(value.Type))
	w.String(string(value.Receiver))
	w.Uint(uint64(len(value.TypeParams)))
	for i0 := range value.TypeParams {
		EncodeIdentityGenericTypeParameter(w, value.TypeParams[i0])
	}
	compiler_ast.EncodeIdentityDecl(w, value.Decl)
	w.Uint(uint64(len(value.References)))
	for i0 := range value.References {
		EncodeIdentityGenericReference(w, value.References[i0])
	}
	w.Uint(uint64(len(value.Expressions)))
	for i0 := range value.Expressions {
		EncodeIdentityGenericExpression(w, value.Expressions[i0])
	}
	w.LeaveStructure()
}

// EncodeIdentityGenericTypeParameter writes the compiler identity schema fields.
func EncodeIdentityGenericTypeParameter(w *identity.Writer, value GenericTypeParameter) {
	if !w.EnterStructure() {
		return
	}
	w.String(string(value.Name))
	w.String(string(value.Binding))
	w.String(string(value.Constraint))
	w.LeaveStructure()
}

// EncodeIdentityPackageData writes the compiler identity schema fields.
func EncodeIdentityPackageData(w *identity.Writer, value PackageData) {
	if !w.EnterStructure() {
		return
	}
	w.String(string(value.Format))
	w.Uint(uint64(value.Version))
	w.String(string(value.ModulePath))
	w.String(string(value.Package))
	w.String(string(value.ArtifactHash))
	w.String(string(value.ExportHash))
	compiler_types.EncodeIdentityTypeTable(w, value.TypeTable)
	w.Uint(uint64(len(value.Constants)))
	for i0 := range value.Constants {
		runtime_bytecode.EncodeIdentityConstant(w, value.Constants[i0])
	}
	w.Uint(uint64(len(value.Exports)))
	for i0 := range value.Exports {
		runtime_bytecode.EncodeIdentityExport(w, value.Exports[i0])
	}
	w.Uint(uint64(len(value.Requirements)))
	for i0 := range value.Requirements {
		runtime_bytecode.EncodeIdentityRequirement(w, value.Requirements[i0])
	}
	w.Uint(uint64(len(value.SourceFiles)))
	for i0 := range value.SourceFiles {
		runtime_bytecode.EncodeIdentitySourceFile(w, value.SourceFiles[i0])
	}
	w.Uint(uint64(len(value.GenericTemplates)))
	for i0 := range value.GenericTemplates {
		EncodeIdentityGenericTemplate(w, value.GenericTemplates[i0])
	}
	w.LeaveStructure()
}

// EncodeIdentityPrepareAction writes the compiler identity schema fields.
func EncodeIdentityPrepareAction(w *identity.Writer, value PrepareAction) {
	if !w.EnterStructure() {
		return
	}
	w.String(string(value.LimitsHash))
	w.String(string(value.Format))
	w.Uint(uint64(value.Version))
	w.String(string(value.Compiler))
	w.String(string(value.Contract))
	compiler_target.EncodeIdentityTarget(w, value.Target)
	w.String(string(value.Mode))
	w.String(string(value.Root))
	w.Bool(value.Entries != nil)
	w.Uint(uint64(len(value.Entries)))
	for i0 := range value.Entries {
		EncodeIdentityEntryPoint(w, value.Entries[i0])
	}
	w.Bool(value.Artifacts != nil)
	w.Uint(uint64(len(value.Artifacts)))
	for i0 := range value.Artifacts {
		EncodeIdentityPrepareArtifact(w, value.Artifacts[i0])
	}
	w.Uint(uint64(len(value.Capabilities)))
	for i0 := range value.Capabilities {
		w.String(string(value.Capabilities[i0]))
	}
	w.LeaveStructure()
}

// EncodeIdentityPrepareArtifact writes the compiler identity schema fields.
func EncodeIdentityPrepareArtifact(w *identity.Writer, value PrepareArtifact) {
	if !w.EnterStructure() {
		return
	}
	w.String(string(value.ModulePath))
	w.String(string(value.Hash))
	w.LeaveStructure()
}

// EncodeIdentitySourceFile writes the compiler identity schema fields.
func EncodeIdentitySourceFile(w *identity.Writer, value SourceFile) {
	if !w.EnterStructure() {
		return
	}
	w.String(string(value.Path))
	w.String(string(value.Hash))
	w.Bool(bool(value.Selected))
	w.LeaveStructure()
}

// EncodeIdentitySymbolAction writes the compiler identity schema fields.
func EncodeIdentitySymbolAction(w *identity.Writer, value SymbolAction) {
	if !w.EnterStructure() {
		return
	}
	w.String(string(value.Format))
	w.Uint(uint64(value.Version))
	w.String(string(value.Compiler))
	w.String(string(value.ProgramHash))
	w.String(string(value.SourceGraphHash))
	w.Uint(uint64(value.Optimization))
	w.LeaveStructure()
}
