package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"reflect"
	"strings"

	"github.com/d7z-team/mini-go/compiler/types"
	"github.com/d7z-team/mini-go/runtime/bytecode"
)

func generateBytecodeJSON() error {
	roots := []any{bytecode.Artifact{}, bytecode.ConstPayload{}, bytecode.LocalPayload{}, bytecode.UpvaluePayload{}, bytecode.GlobalPayload{}, bytecode.AddressPayload{}, bytecode.TypePayload{}, bytecode.OperatorPayload{}, bytecode.MakeSequencePayload{}, bytecode.MakeMapPayload{}, bytecode.MakeStructPayload{}, bytecode.MakeSlicePayload{}, bytecode.MakeWaitablePayload{}, bytecode.SelectPayload{}, bytecode.CountPayload{}, bytecode.FieldPayload{}, bytecode.ExportPayload{}, bytecode.InitModulePayload{}, bytecode.LabelPayload{}, bytecode.JumpPayload{}, bytecode.CallPayload{}, bytecode.CallInterfacePayload{}, bytecode.ClosurePayload{}, bytecode.ReturnPayload{}, bytecode.DeferPayload{}, bytecode.CallFFIPayload{}, bytecode.CallIntrinsicPayload{}}
	roots = append(roots, types.TypeRef{})
	roots = append(roots, bytecode.Instruction{})
	roots = append(roots, bytecode.TypeDispatchPayload{})
	roots = append(roots, bytecode.CompareBranchPayload{})
	roots = append(roots, bytecode.FieldPathPayload{})
	roots = append(roots, bytecode.SlotCode{})
	roots = append(roots, bytecode.ExecutionImage{}, bytecode.ProgramSymbols{})
	// Payload roots define the instruction descriptor union. Its codec belongs
	// to the image boundary; compiler and runtime stages keep the typed values.
	payloads := []reflect.Type{}
	for _, root := range roots {
		t := reflect.TypeOf(root)
		if strings.HasSuffix(t.Name(), "Payload") {
			payloads = append(payloads, t)
		}
	}
	rawType := reflect.TypeOf(json.RawMessage{})
	structures, err := schemaStructures(roots)
	if err != nil {
		return err
	}
	name := func(t reflect.Type) string {
		if t.PkgPath() == reflect.TypeOf(bytecode.Artifact{}).PkgPath() {
			return t.Name()
		}
		return t.String()
	}
	var out bytes.Buffer
	out.WriteString("// Code generated by mini-go-dev bytecode-json; DO NOT EDIT.\npackage bytecode\nimport (\"bytes\"; \"encoding/json\"; \"fmt\"; \"strings\"; \"strconv\"; \"sort\"; \"github.com/d7z-team/mini-go/compiler/types\"; \"github.com/d7z-team/mini-go/compiler/target\")\n")
	out.WriteString("func encodeFixedJSON(value any) ([]byte,error,bool) {\nw := canonicalBuffer{}\nswitch v := value.(type) {\n")
	for _, root := range roots {
		t := reflect.TypeOf(root)
		fmt.Fprintf(&out, "case %s: w.encode%s(&v)\ncase *%s: if v == nil {w.data=append(w.data,\"null\"...)} else {w.encode%s(v)}\n", name(t), t.Name(), name(t), t.Name())
	}
	out.WriteString("default: return nil,nil,false\n}\nreturn w.data,w.err,true\n}\n")
	var emit func(reflect.Type, string, int) error
	emit = func(t reflect.Type, value string, depth int) error {
		if t == reflect.TypeOf(bytecode.OpConst) {
			fmt.Fprintf(&out, "w.string(%s.String())\n", value)
			return nil
		}
		if value == "v.Payload" {
			out.WriteString("w.payload(v.Payload)\n")
			return nil
		}
		if t == rawType {
			fmt.Fprintf(&out, "w.raw(%s)\n", value)
			return nil
		}
		switch t.Kind() {
		case reflect.Map:
			fmt.Fprintf(&out, "if %s==nil {w.data=append(w.data,\"null\"...)} else {\nkeys%d:=make([]string,0,len(%s))\nfor key:=range %s {keys%d=append(keys%d,string(key))}\nsort.Strings(keys%d)\nw.data=append(w.data,'{')\nfor i%d,key%d:=range keys%d {if i%d>0 {w.data=append(w.data,',')}\nw.string(key%d)\nw.data=append(w.data,':')\nvalue%d:=%s[key%d]\n", value, depth, value, value, depth, depth, depth, depth, depth, depth, depth, depth, depth, value, depth)
			if err := emit(t.Elem(), fmt.Sprintf("value%d", depth), depth+1); err != nil {
				return err
			}
			out.WriteString("}\nw.data=append(w.data,'}')}\n")
		case reflect.Struct:
			fmt.Fprintf(&out, "w.encode%s(&%s)\n", t.Name(), value)
		case reflect.Pointer:
			fmt.Fprintf(&out, "if %s == nil {w.data=append(w.data,\"null\"...)} else {\n", value)
			if err := emit(t.Elem(), "(*"+value+")", depth+1); err != nil {
				return err
			}
			out.WriteString("}\n")
		case reflect.Slice, reflect.Array:
			if t.Kind() == reflect.Slice {
				fmt.Fprintf(&out, "if %s == nil {w.data=append(w.data,\"null\"...)} else {\n", value)
			}
			fmt.Fprintf(&out, "w.data=append(w.data,'[')\nfor i%d := range %s {if i%d > 0 {w.data=append(w.data,',')}\n", depth, value, depth)
			if err := emit(t.Elem(), fmt.Sprintf("%s[i%d]", value, depth), depth+1); err != nil {
				return err
			}
			out.WriteString("}\nw.data=append(w.data,']')\n")
			if t.Kind() == reflect.Slice {
				out.WriteString("}\n")
			}
		case reflect.String:
			fmt.Fprintf(&out, "w.string(string(%s))\n", value)
		case reflect.Bool:
			fmt.Fprintf(&out, "w.data=strconv.AppendBool(w.data,bool(%s))\n", value)
		case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
			fmt.Fprintf(&out, "w.data=strconv.AppendInt(w.data,int64(%s),10)\n", value)
		default:
			fmt.Fprintf(&out, "w.data=strconv.AppendUint(w.data,uint64(%s),10)\n", value)
		}
		return nil
	}
	for _, t := range structures {
		if t == reflect.TypeFor[bytecode.SlotInstruction]() || t == reflect.TypeFor[bytecode.Operand]() {
			fmt.Fprintf(&out, "func(w *canonicalBuffer) encode%s(v *%s) {w.data=append(w.data,'[')\n", t.Name(), name(t))
			for index := range t.NumField() {
				if index != 0 {
					out.WriteString("w.data=append(w.data,',')\n")
				}
				fmt.Fprintf(&out, "w.data=strconv.AppendUint(w.data,uint64(v.%s),10)\n", t.Field(index).Name)
			}
			out.WriteString("w.data=append(w.data,']')}\n")
			continue
		}
		fmt.Fprintf(&out, "func(w *canonicalBuffer) encode%s(v *%s) {\n", t.Name(), name(t))
		if t == reflect.TypeFor[types.TypeRef]() {
			out.WriteString("if cached,ok:=w.typeRefs[*v]; ok {w.data=append(w.data,cached...);return}\nstart:=len(w.data)\n")
		}
		out.WriteString("w.data=append(w.data,'{')\n")
		out.WriteString("comma := false\n_ = comma\n")
		fields := make([]reflect.StructField, t.NumField())
		for i := 0; i < t.NumField(); i++ {
			fields[i] = t.Field(i)
		}
		if t == reflect.TypeFor[bytecode.DescriptorTables]() {
			// This table is generated by this same command. Derive its fields
			// from the payload roots so one run includes newly added payloads.
			fields = fields[:0]
			for _, payload := range payloads {
				field := strings.TrimSuffix(payload.Name(), "Payload")
				fields = append(fields, reflect.StructField{Name: field, Type: reflect.SliceOf(payload), Tag: reflect.StructTag(`json:"` + strings.ToLower(field) + `,omitempty"`)})
			}
		}
		for _, f := range fields {
			tag := strings.Split(f.Tag.Get("json"), ",")
			if !f.IsExported() || tag[0] == "-" {
				continue
			}
			key := tag[0]
			if key == "" {
				key = f.Name
			}
			value := "v." + f.Name
			condition := ""
			for _, option := range tag[1:] {
				if option != "omitempty" {
					return fmt.Errorf("unsupported JSON option %q on %v.%s", option, t, f.Name)
				}
				switch f.Type.Kind() {
				case reflect.String, reflect.Slice, reflect.Map:
					condition = "len(" + value + ") != 0"
				case reflect.Bool:
					condition = value
				case reflect.Pointer:
					condition = value + " != nil"
				case reflect.Struct:
				default:
					condition = value + " != 0"
				}
			}
			if t.Name() == "Instruction" && f.Name == "Payload" {
				condition = value + " != nil"
			}
			if condition != "" {
				fmt.Fprintf(&out, "if %s {\n", condition)
			}
			encoded, _ := json.Marshal(key)
			fmt.Fprintf(&out, "if comma {w.data=append(w.data,',')}\ncomma=true\nw.data=append(w.data,%q...)\n", string(encoded)+":")
			if t == reflect.TypeFor[bytecode.PackageArchive]() && f.Name == "Artifact" {
				out.WriteString("if v.hasCanonicalProof() {w.data=append(w.data,v.Artifact...)} else {w.raw(v.Artifact)}\n")
			} else if t.Name() == "SlotInstruction" && f.Name == "Op" {
				fmt.Fprintf(&out, "w.data=strconv.AppendUint(w.data,uint64(%s),10)\n", value)
			} else if err := emit(f.Type, value, 0); err != nil {
				return err
			}
			if condition != "" {
				out.WriteString("}\n")
			}
		}
		out.WriteString("w.data=append(w.data,'}')\n")
		if t == reflect.TypeFor[types.TypeRef]() {
			out.WriteString("if len(w.typeRefs)<1024 && w.typeRefBytes+len(w.data)-start<=256<<10 {if w.typeRefs==nil {w.typeRefs=make(map[types.TypeRef]string)}; w.typeRefs[*v]=string(w.data[start:]);w.typeRefBytes+=len(w.data)-start}\n")
		}
		out.WriteString("}\n")
	}
	// Decoding is restricted to payload roots. Nested values retain the strict
	// standard decoder, while small scalar fields avoid struct tag reflection.
	out.WriteString("// decodeFixedPayload requires syntactically valid JSON from its caller.\nfunc decodeFixedPayload(raw []byte, output any) (bool,error) {\nraw=bytes.TrimSpace(raw)\nif len(raw)==0 || raw[0]!='{' {return false,nil}\nswitch v:=output.(type) {\n")
	for _, root := range roots[1:] {
		t := reflect.TypeOf(root)
		fmt.Fprintf(&out, "case *%s:\nif v==nil {return false,nil}\nr:=payloadObject{raw:raw,pos:1}\nfor r.next() {\nvar err error\nswitch {\n", name(t))
		for i := 0; i < t.NumField(); i++ {
			f := t.Field(i)
			key := strings.Split(f.Tag.Get("json"), ",")[0]
			if !f.IsExported() || key == "-" {
				continue
			}
			if key == "" {
				key = f.Name
			}
			fmt.Fprintf(&out, "case r.name==%q || strings.EqualFold(r.name,%q):\n", key, key)
			bits := 0
			if f.Type.Kind() >= reflect.Int8 && f.Type.Kind() <= reflect.Int64 || f.Type.Kind() >= reflect.Uint8 && f.Type.Kind() <= reflect.Uint64 {
				bits = f.Type.Bits()
			}
			switch f.Type.Kind() {
			case reflect.String:
				fmt.Fprintf(&out, "if text,plain:=plainPayloadString(r.value); plain {v.%s=%s(text)} else {err=json.Unmarshal(r.value,&v.%s)}\n", f.Name, name(f.Type), f.Name)
			case reflect.Bool:
				fmt.Fprintf(&out, "switch string(bytes.TrimSpace(r.value)) {case \"true\":v.%s=true;case \"false\":v.%s=false;case \"null\":default:err=json.Unmarshal(r.value,&v.%s)}\n", f.Name, f.Name, f.Name)
			case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
				fmt.Fprintf(&out, "if text:=string(bytes.TrimSpace(r.value));text!=\"null\" {parsed,parseErr:=strconv.ParseInt(text,10,%d);if parseErr==nil {v.%s=%s(parsed)} else {err=json.Unmarshal(r.value,&v.%s)}}\n", bits, f.Name, name(f.Type), f.Name)
			case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
				fmt.Fprintf(&out, "if text:=string(bytes.TrimSpace(r.value));text!=\"null\" {parsed,parseErr:=strconv.ParseUint(text,10,%d);if parseErr==nil {v.%s=%s(parsed)} else {err=json.Unmarshal(r.value,&v.%s)}}\n", bits, f.Name, name(f.Type), f.Name)
			case reflect.Struct:
				fmt.Fprintf(&out, "err=DecodeInstructionPayload(r.value,&v.%s)\n", f.Name)
			default:
				fmt.Fprintf(&out, "err=strictUnmarshal(r.value,&v.%s)\n", f.Name)
			}
		}
		out.WriteString("default: return true,fmt.Errorf(\"json: unknown field %q\",r.name)\n}\nif err!=nil{return true,err}\n}\nreturn true,nil\n")
	}
	out.WriteString("default: return false,nil\n}\n}\n")
	for _, t := range payloads {
		fmt.Fprintf(&out, "func (%s) instructionPayload() {}\n", t.Name())
	}
	var size func(reflect.Type, string, int)
	size = func(t reflect.Type, value string, depth int) {
		switch t.Kind() {
		case reflect.String:
			fmt.Fprintf(&out, "n+=16+len(%s)\n", value)
		case reflect.Slice:
			fmt.Fprintf(&out, "n+=24\nfor j%d:=range %s {\n_ = j%d\n", depth, value, depth)
			size(t.Elem(), fmt.Sprintf("%s[j%d]", value, depth), depth+1)
			out.WriteString("}\n")
		case reflect.Struct:
			for i := 0; i < t.NumField(); i++ {
				size(t.Field(i).Type, value+"."+t.Field(i).Name, depth)
			}
		case reflect.Bool, reflect.Uint8, reflect.Int8:
			out.WriteString("n++\n")
		default:
			out.WriteString("n+=8\n")
		}
	}
	for _, t := range payloads {
		fmt.Fprintf(&out, "func(v %s) descriptorBytes() int {n:=0\n", t.Name())
		size(t, "v", 0)
		out.WriteString("return n\n}\n")
	}
	var clone func(reflect.Type, string, int)
	clone = func(t reflect.Type, value string, depth int) {
		switch t.Kind() {
		case reflect.Slice:
			fmt.Fprintf(&out, "if %s!=nil {%s=append(make(%s,0,len(%s)),%s...)}\n", value, value, strings.ReplaceAll(t.String(), "bytecode.", ""), value, value)
			if t.Elem().Kind() == reflect.Struct || t.Elem().Kind() == reflect.Slice {
				fmt.Fprintf(&out, "for j%d:=range %s {\n_ = j%d\n", depth, value, depth)
				clone(t.Elem(), fmt.Sprintf("%s[j%d]", value, depth), depth+1)
				out.WriteString("}\n")
			}
		case reflect.Struct:
			for i := 0; i < t.NumField(); i++ {
				clone(t.Field(i).Type, value+"."+t.Field(i).Name, depth)
			}
		}
	}
	out.WriteString("func clonePayload(value Payload) Payload {switch v:=value.(type) {\n")
	for _, t := range payloads {
		fmt.Fprintf(&out, "case %s:\n", t.Name())
		clone(t, "v", 0)
		out.WriteString("return v\n")
	}
	out.WriteString("default:return value\n}}\n")
	out.WriteString("func descriptorBytes(value Payload) int {switch v:=value.(type) {\n")
	for _, t := range payloads {
		fmt.Fprintf(&out, "case %s:return v.descriptorBytes()\n", t.Name())
	}
	out.WriteString("default:return 0\n}}\n")
	out.WriteString("func(w *canonicalBuffer) payload(value Payload) {switch v:=value.(type) {\ncase nil: w.data=append(w.data,\"null\"...)\n")
	for _, t := range payloads {
		fmt.Fprintf(&out, "case %s: w.encode%s(&v)\n", t.Name(), t.Name())
	}
	out.WriteString("default: w.err=fmt.Errorf(\"unsupported instruction payload %T\",value)\n}}\n")
	out.WriteString("// ReadInstructionPayload copies a typed instruction descriptor.\nfunc ReadInstructionPayload(value Payload, output any) error {switch v:=output.(type) {\n")
	for _, t := range payloads {
		fmt.Fprintf(&out, "case *%s: if p,ok:=value.(%s);ok && v!=nil {*v=p;return nil}\n", t.Name(), t.Name())
	}
	out.WriteString("}\nreturn fmt.Errorf(\"instruction payload %T does not match %T\",value,output)\n}\n")
	out.WriteString("func decodePayload(op string, raw json.RawMessage) (Payload,error) {if len(raw)==0{return nil,nil};switch op {\n")
	for _, spec := range bytecode.CurrentSpec().Opcodes {
		if spec.Payload == "" {
			continue
		}
		payloadName := ""
		for _, t := range payloads {
			if strings.ToLower(strings.TrimSuffix(t.Name(), "Payload")) == strings.ReplaceAll(spec.Payload, "_", "") {
				payloadName = t.Name()
			}
		}
		if payloadName == "" {
			return fmt.Errorf("missing descriptor model for %s", spec.Payload)
		}
		fmt.Fprintf(&out, "case %q: var v %s; if err:=DecodeInstructionPayload(raw,&v);err!=nil{return nil,err};return v,nil\n", spec.Op, payloadName)
	}
	out.WriteString("default: if len(bytes.TrimSpace(raw))==0 || string(bytes.TrimSpace(raw))==\"{}\" {return nil,nil};return nil,fmt.Errorf(\"opcode %q does not accept a payload\",op)\n}}\n")
	formatted, err := format.Source(out.Bytes())
	if err != nil {
		return err
	}
	if err := os.WriteFile("runtime/bytecode/canonical_generated.go", formatted, 0o644); err != nil {
		return err
	}
	return generateDescriptorTables(payloads)
}

// Tables keep canonical descriptors as concrete values, independently of the
// fixed instruction stream. Boxing is confined to builder/prepare dispatch.
func generateDescriptorTables(payloads []reflect.Type) error {
	var out bytes.Buffer
	out.WriteString("// Code generated by mini-go-dev bytecode-json; DO NOT EDIT.\npackage bytecode\nimport \"fmt\"\ntype DescriptorTables struct {\n")
	for _, typ := range payloads {
		name := strings.TrimSuffix(typ.Name(), "Payload")
		fmt.Fprintf(&out, "%s []%s `json:%q`\n", name, typ.Name(), strings.ToLower(name)+",omitempty")
	}
	out.WriteString("}\nfunc(t *DescriptorTables) Append(value Payload) (uint32,error) {switch v:=value.(type) {case nil:return 0,nil\n")
	for _, typ := range payloads {
		name := strings.TrimSuffix(typ.Name(), "Payload")
		fmt.Fprintf(&out, "case %s: if uint64(len(t.%s))>=1<<32 {return 0,fmt.Errorf(\"descriptor table exceeds uint32\")}; index:=uint32(len(t.%s));t.%s=append(t.%s,v);return index,nil\n", typ.Name(), name, name, name, name)
	}
	out.WriteString("};return 0,fmt.Errorf(\"unsupported descriptor %T\",value)}\n")
	out.WriteString("func(t *DescriptorTables) Payload(op Opcode,index uint32) (Payload,error) {switch op {\n")
	for _, spec := range bytecode.CurrentSpec().Opcodes {
		op, _ := bytecode.ParseOpcode(spec.Op)
		fmt.Fprintf(&out, "case Opcode(%d):\n", op)
		if spec.Payload == "" {
			out.WriteString("if index==0{return nil,nil}\n")
			continue
		}
		for _, typ := range payloads {
			name := strings.TrimSuffix(typ.Name(), "Payload")
			if strings.ToLower(name) == strings.ReplaceAll(spec.Payload, "_", "") {
				fmt.Fprintf(&out, "if uint64(index)<uint64(len(t.%s)) {return t.%s[index],nil}\n", name, name)
				break
			}
		}
	}
	out.WriteString("};return nil,fmt.Errorf(\"invalid descriptor %d for opcode %s\",index,op)}\n")
	out.WriteString("func(t *DescriptorTables) Clone() DescriptorTables {out:=DescriptorTables{}\n")
	for _, typ := range payloads {
		name := strings.TrimSuffix(typ.Name(), "Payload")
		fmt.Fprintf(&out, "if t.%s!=nil {out.%s=make([]%s,len(t.%s));for i,v:=range t.%s {out.%s[i]=clonePayload(v).(%s)}}\n", name, name, typ.Name(), name, name, name, typ.Name())
	}
	out.WriteString("return out}\nfunc(t *DescriptorTables) Bytes() int {total:=0\n")
	for _, typ := range payloads {
		name := strings.TrimSuffix(typ.Name(), "Payload")
		fmt.Fprintf(&out, "for _,v:=range t.%s {total+=v.descriptorBytes()}\n", name)
	}
	out.WriteString("return total}\n")
	formatted, err := format.Source(out.Bytes())
	if err != nil {
		return err
	}
	return os.WriteFile("runtime/bytecode/descriptors_generated.go", formatted, 0o644)
}
