package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"flag"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func runCompilerIdentity(args []string, stderr io.Writer) error {
	flags := flag.NewFlagSet("mini-go-dev compiler-identity", flag.ContinueOnError)
	flags.SetOutput(stderr)
	output := flags.String("out", "", "generated Go source")
	check := flags.Bool("check", false, "verify the generated identity without writing")
	if err := flags.Parse(args); err != nil {
		return err
	}
	if flags.NArg() != 0 || strings.TrimSpace(*output) == "" {
		return errors.New("compiler-identity requires -out")
	}

	paths := []string{"go.mod"}
	if _, err := os.Stat("go.sum"); err == nil {
		paths = append(paths, "go.sum")
	} else if !errors.Is(err, os.ErrNotExist) {
		return err
	}
	for _, root := range []string{"compiler", "runtime/bytecode"} {
		err := filepath.WalkDir(root, func(path string, entry fs.DirEntry, walkErr error) error {
			if walkErr != nil {
				return walkErr
			}
			if entry.IsDir() {
				return nil
			}
			name := entry.Name()
			if path == filepath.Clean(*output) || strings.HasSuffix(name, "_test.go") || strings.HasSuffix(name, "_test.mgo") {
				return nil
			}
			if strings.HasSuffix(name, ".go") || strings.HasSuffix(name, ".mgo") {
				paths = append(paths, filepath.ToSlash(path))
			}
			return nil
		})
		if err != nil {
			return err
		}
	}
	sort.Strings(paths)
	hash := sha256.New()
	for _, path := range paths {
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		fmt.Fprintf(hash, "%s\x00%d\x00", filepath.ToSlash(path), len(data))
		if _, err := hash.Write(data); err != nil {
			return err
		}
	}
	identity := hex.EncodeToString(hash.Sum(nil))
	generated := fmt.Sprintf("// Code generated by mini-go compiler-identity; DO NOT EDIT.\n\npackage bytecode\n\n// CompilerIdentity identifies the compiler and bytecode semantics used by caches.\nconst CompilerIdentity = %q\n", identity)
	if *check {
		current, err := os.ReadFile(*output)
		if errors.Is(err, fs.ErrNotExist) {
			return fmt.Errorf("missing compiler identity %s; run make generate", *output)
		}
		if err != nil {
			return err
		}
		if !bytes.Equal(current, []byte(generated)) {
			return errors.New("compiler identity is stale; run make generate")
		}
		return nil
	}
	return writeGeneratedFile(*output, []byte(generated))
}
