package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"

	"github.com/d7z-team/mini-go/compiler/cache"
	"github.com/d7z-team/mini-go/compiler/semantic"
)

// generateCompilerBinary emits only the fixed compiler identity graph. Reflection
// is used by this maintenance command, never by the compiler identity encoder.
func generateCompilerBinary() error {
	const prefix = "github.com/d7z-team/mini-go/"
	groups := map[string][]reflect.Type{}
	structures, err := schemaStructures([]any{cache.PackageData{}, cache.Action{}, cache.PrepareAction{}, cache.SymbolAction{}, semantic.DependencyPackage{}})
	if err != nil {
		return err
	}
	for _, t := range structures {
		if !strings.HasPrefix(t.PkgPath(), prefix) || t.Name() == "" {
			return fmt.Errorf("unsupported identity structure %v", t)
		}
		groups[t.PkgPath()] = append(groups[t.PkgPath()], t)
	}
	for path, types := range groups {
		sort.Slice(types, func(i, j int) bool { return types[i].Name() < types[j].Name() })
		imports := map[string]string{}
		var body bytes.Buffer
		var emit func(reflect.Type, string, int)
		emit = func(t reflect.Type, value string, depth int) {
			if t == reflect.TypeOf(json.RawMessage{}) {
				fmt.Fprintf(&body, "w.JSON(%s)\n", value)
				return
			}
			if t.Kind() == reflect.Slice && t.Elem() == reflect.TypeOf(byte(0)) {
				fmt.Fprintf(&body, "w.Bytes(%s)\n", value)
				return
			}
			switch t.Kind() {
			case reflect.Struct:
				qualifier := ""
				if t.PkgPath() != path {
					alias := strings.ReplaceAll(strings.TrimPrefix(t.PkgPath(), prefix), "/", "_")
					imports[t.PkgPath()] = alias
					qualifier = alias + "."
				}
				fmt.Fprintf(&body, "%sEncodeIdentity%s(w, %s)\n", qualifier, t.Name(), value)
			case reflect.Pointer:
				fmt.Fprintf(&body, "w.Bool(%s != nil)\nif %s != nil {\n", value, value)
				emit(t.Elem(), "(*"+value+")", depth+1)
				body.WriteString("}\n")
			case reflect.Slice, reflect.Array:
				fmt.Fprintf(&body, "w.Uint(uint64(len(%s)))\nfor i%d := range %s {\n", value, depth, value)
				emit(t.Elem(), fmt.Sprintf("%s[i%d]", value, depth), depth+1)
				body.WriteString("}\n")
			case reflect.String:
				fmt.Fprintf(&body, "w.String(string(%s))\n", value)
			case reflect.Bool:
				fmt.Fprintf(&body, "w.Bool(bool(%s))\n", value)
			default:
				fmt.Fprintf(&body, "w.Uint(uint64(%s))\n", value)
			}
		}
		for _, t := range types {
			fmt.Fprintf(&body, "// EncodeIdentity%s writes the compiler identity schema fields.\nfunc EncodeIdentity%s(w *identity.Writer, value %s) {\n", t.Name(), t.Name(), t.Name())
			body.WriteString("if !w.EnterStructure() { return }\n")
			for i := 0; i < t.NumField(); i++ {
				f := t.Field(i)
				if f.IsExported() && f.Tag.Get("json") != "-" {
					if f.Type.Kind() == reflect.Slice && f.Type != reflect.TypeOf(json.RawMessage{}) && !strings.Contains(","+f.Tag.Get("json")+",", ",omitempty,") {
						fmt.Fprintf(&body, "w.Bool(value.%s != nil)\n", f.Name)
					}
					emit(f.Type, "value."+f.Name, 0)
				}
			}
			body.WriteString("w.LeaveStructure()\n}\n")
		}
		var file bytes.Buffer
		fmt.Fprintf(&file, "// Code generated by mini-go-dev compiler-binary; DO NOT EDIT.\npackage %s\nimport (\n%q\n", types[0].String()[:strings.IndexByte(types[0].String(), '.')], prefix+"compiler/identity")
		paths := make([]string, 0, len(imports))
		for p := range imports {
			paths = append(paths, p)
		}
		sort.Strings(paths)
		for _, p := range paths {
			fmt.Fprintf(&file, "%s %q\n", imports[p], p)
		}
		file.WriteString(")\n")
		file.Write(body.Bytes())
		formatted, err := format.Source(file.Bytes())
		if err != nil {
			return err
		}
		if err = os.WriteFile(filepath.Join(strings.TrimPrefix(path, prefix), "identity_generated.go"), formatted, 0o644); err != nil {
			return err
		}
	}
	return nil
}
