package main

import (
	"bytes"
	"compress/gzip"
	"crypto/sha256"
	_ "embed"
	"encoding/binary"
	"errors"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io"
	"sort"
	"strconv"
	"strings"

	miniformat "github.com/d7z-team/mini-go/compiler/format"
)

// Source: https://raw.githubusercontent.com/golang/go/go1.27.1/src/unicode/tables.go
// The Go Authors' BSD license is preserved in stdlib/LICENSE_GO.
//
//go:embed data/unicode/go1.27.1-tables.go.gz
var unicodeSource []byte

func unicodeTables() ([]byte, map[string][][3]uint32, error) {
	reader, err := gzip.NewReader(bytes.NewReader(unicodeSource))
	if err != nil {
		return nil, nil, err
	}
	data, err := io.ReadAll(reader)
	closeErr := reader.Close()
	if err != nil {
		return nil, nil, err
	}
	if closeErr != nil {
		return nil, nil, closeErr
	}
	if fmt.Sprintf("%x", sha256.Sum256(data)) != "ac0e5d5d1b58ed4b02d7cb4a0085bdefbdb4f7aae6fadddbc9477f8463da8bd8" {
		return nil, nil, errors.New("Unicode 17 source checksum mismatch")
	}
	file, err := parser.ParseFile(token.NewFileSet(), "tables.go", data, 0)
	if err != nil {
		return nil, nil, err
	}
	tables := make(map[string][][3]uint32)
	for _, declaration := range file.Decls {
		group, ok := declaration.(*ast.GenDecl)
		if !ok || group.Tok != token.VAR {
			continue
		}
		for _, spec := range group.Specs {
			value := spec.(*ast.ValueSpec)
			name := value.Names[0].Name
			if name != "_L" && name != "_Nd" && name != "_Lu" {
				continue
			}
			literal := value.Values[0].(*ast.UnaryExpr).X.(*ast.CompositeLit)
			for _, element := range literal.Elts {
				field := element.(*ast.KeyValueExpr)
				if field.Key.(*ast.Ident).Name == "LatinOffset" {
					continue
				}
				for _, element := range field.Value.(*ast.CompositeLit).Elts {
					var row [3]uint32
					for i, expression := range element.(*ast.CompositeLit).Elts {
						v, err := strconv.ParseUint(expression.(*ast.BasicLit).Value, 0, 32)
						if err != nil {
							return nil, nil, err
						}
						row[i] = uint32(v)
					}
					tables[name] = append(tables[name], row)
				}
			}
		}
	}
	return data, tables, nil
}

func generateUnicode() error {
	data, tables, err := unicodeTables()
	if err != nil {
		return err
	}
	packed, resource, err := packUnicodeTables(data)
	if err != nil {
		return err
	}
	formatted := miniformat.Source("unicode", "tables.mgo", string(packed))
	if len(formatted.Diagnostics) != 0 {
		return fmt.Errorf("format Unicode tables: %v", formatted.Diagnostics)
	}
	if err := writeGeneratedFile("stdlib/src/unicode/tables.mgo", []byte(formatted.Text)); err != nil {
		return err
	}
	if err := writeGeneratedFile("stdlib/src/unicode/ranges.bin", resource); err != nil {
		return err
	}
	var goSource, rustSource strings.Builder
	goSource.WriteString("// Code generated by mini-go-dev unicode; DO NOT EDIT.\n// Unicode 17.0.0, Go Authors BSD license: stdlib/LICENSE_GO.\npackage token\n\nconst UnicodeVersion = \"17.0.0\"\n")
	rustSource.WriteString("// Code generated by mini-go-dev unicode; DO NOT EDIT.\n// Unicode 17.0.0, Go Authors BSD license: stdlib/LICENSE_GO.\n")
	for _, table := range []struct{ source, name string }{{"_L", "letter"}, {"_Nd", "digit"}, {"_Lu", "upper"}} {
		fmt.Fprintf(&goSource, "var %sRanges = [][3]uint32{\n", table.name)
		fmt.Fprintf(&rustSource, "pub(super) const %s: &[[u32; 3]] = &[\n", strings.ToUpper(table.name))
		for _, row := range tables[table.source] {
			fmt.Fprintf(&goSource, "{0x%x, 0x%x, %d},\n", row[0], row[1], row[2])
			fmt.Fprintf(&rustSource, "    [0x%x, 0x%x, %d],\n", row[0], row[1], row[2])
		}
		goSource.WriteString("}\n")
		rustSource.WriteString("];\n")
	}
	goData, err := format.Source([]byte(goSource.String()))
	if err != nil {
		return err
	}
	if err := writeGeneratedFile("compiler/token/unicode_generated.go", goData); err != nil {
		return err
	}
	return writeGeneratedFile("playground/runtime-rust/src/types/names_generated.rs", []byte(rustSource.String()))
}

// packUnicodeTables replaces only data literals. Keeping the surrounding
// declarations preserves public aliases and the upstream documentation.
func packUnicodeTables(data []byte) ([]byte, []byte, error) {
	positions := token.NewFileSet()
	file, err := parser.ParseFile(positions, "tables.go", data, 0)
	if err != nil {
		return nil, nil, err
	}
	type replacement struct {
		start, end int
		text       string
	}
	edits := []replacement{{
		positions.Position(file.Name.End()).Offset, positions.Position(file.Name.End()).Offset,
		"\n\nimport _ \"embed\"\n\n//go:embed ranges.bin\nvar rangeData []byte\n",
	}}
	var resource []byte
	number := func(expr ast.Expr) (int64, error) {
		if name, ok := expr.(*ast.Ident); ok && name.Name == "UpperLower" {
			return 0x110000, nil
		}
		var text bytes.Buffer
		if err := format.Node(&text, positions, expr); err != nil {
			return 0, err
		}
		return strconv.ParseInt(text.String(), 0, 64)
	}
	for _, declaration := range file.Decls {
		group, ok := declaration.(*ast.GenDecl)
		if !ok || group.Tok != token.VAR {
			continue
		}
		for _, spec := range group.Specs {
			value := spec.(*ast.ValueSpec)
			if len(value.Values) != 1 {
				continue
			}
			expr := value.Values[0]
			start := len(resource)
			decoder := ""
			if address, ok := expr.(*ast.UnaryExpr); ok && address.Op == token.AND {
				literal, ok := address.X.(*ast.CompositeLit)
				if !ok {
					continue
				}
				typ, ok := literal.Type.(*ast.Ident)
				if !ok || typ.Name != "RangeTable" {
					continue
				}
				var flags byte
				var latin int64
				var ranges [2][]byte
				var counts [2]int
				for _, element := range literal.Elts {
					field := element.(*ast.KeyValueExpr)
					name := field.Key.(*ast.Ident).Name
					if name == "LatinOffset" {
						latin, err = number(field.Value)
						if err != nil {
							return nil, nil, err
						}
						continue
					}
					index, width := 0, 2
					if name == "R32" {
						index, width = 1, 4
					} else if name != "R16" {
						return nil, nil, fmt.Errorf("unknown range field %s", name)
					}
					flags |= 1 << index
					rows := field.Value.(*ast.CompositeLit).Elts
					counts[index] = len(rows)
					if len(rows) > 65535 {
						return nil, nil, errors.New("Unicode range count exceeds uint16")
					}
					for _, row := range rows {
						cells := row.(*ast.CompositeLit).Elts
						if len(cells) != 3 {
							return nil, nil, errors.New("invalid Unicode range")
						}
						for _, cell := range cells {
							n, err := number(cell)
							if err != nil {
								return nil, nil, err
							}
							if n < 0 || uint64(n) >= uint64(1)<<(width*8) {
								return nil, nil, errors.New("Unicode range field overflow")
							}
							if width == 2 {
								ranges[index] = binary.BigEndian.AppendUint16(ranges[index], uint16(n))
							} else {
								ranges[index] = binary.BigEndian.AppendUint32(ranges[index], uint32(n))
							}
						}
					}
				}
				if latin < 0 || latin > int64(counts[0]) {
					return nil, nil, errors.New("invalid Unicode LatinOffset")
				}
				resource = append(resource, flags)
				for _, n := range []int{counts[0], counts[1], int(latin)} {
					resource = binary.BigEndian.AppendUint16(resource, uint16(n))
				}
				resource = append(resource, ranges[0]...)
				resource = append(resource, ranges[1]...)
				decoder = "unpackRangeTable"
			} else if value.Names[0].Name == "_CaseRanges" {
				literal := expr.(*ast.CompositeLit)
				for _, row := range literal.Elts {
					cells := row.(*ast.CompositeLit).Elts
					if len(cells) != 3 {
						return nil, nil, errors.New("invalid Unicode case range")
					}
					values := append([]ast.Expr{cells[0], cells[1]}, cells[2].(*ast.CompositeLit).Elts...)
					if len(values) != 5 {
						return nil, nil, errors.New("invalid Unicode case delta")
					}
					for i, cell := range values {
						n, err := number(cell)
						if err != nil {
							return nil, nil, err
						}
						if n < -1<<31 || n > 1<<31-1 || i < 2 && n < 0 {
							return nil, nil, errors.New("Unicode case field overflow")
						}
						resource = binary.BigEndian.AppendUint32(resource, uint32(n))
					}
				}
				decoder = "unpackCaseRanges"
			}
			if decoder != "" {
				edits = append(edits, replacement{
					positions.Position(expr.Pos()).Offset, positions.Position(expr.End()).Offset,
					fmt.Sprintf("%s(rangeData[%d:%d])", decoder, start, len(resource)),
				})
			}
		}
	}
	sort.Slice(edits, func(i, j int) bool { return edits[i].start > edits[j].start })
	for _, edit := range edits {
		data = append(append(append([]byte(nil), data[:edit.start]...), edit.text...), data[edit.end:]...)
	}
	var decoder strings.Builder
	decoder.WriteString(`
func unpackRangeTable(data []byte) *RangeTable {
    n16 := int(data[1])<<8 | int(data[2])
    n32 := int(data[3])<<8 | int(data[4])
    var r16 []Range16
    var r32 []Range32
    if data[0]&1 != 0 { r16 = make([]Range16, n16) }
    if data[0]&2 != 0 { r32 = make([]Range32, n32) }
    p := 7
`)
	for _, bits := range []int{16, 32} {
		fmt.Fprintf(&decoder, "for i := range r%d { r%d[i] = Range%d{", bits, bits, bits)
		for field := 0; field < 3; field++ {
			if field > 0 {
				decoder.WriteByte(',')
			}
			for b := 0; b < bits/8; b++ {
				if b > 0 {
					decoder.WriteByte('|')
				}
				offset := field*bits/8 + b
				index := "p"
				if offset != 0 {
					index += "+" + strconv.Itoa(offset)
				}
				fmt.Fprintf(&decoder, "uint%d(data[%s])", bits, index)
				if shift := bits - 8 - b*8; shift != 0 {
					fmt.Fprintf(&decoder, "<<%d", shift)
				}
			}
		}
		fmt.Fprintf(&decoder, "}; p += %d }\n", bits/8*3)
	}
	decoder.WriteString("return &RangeTable{R16:r16,R32:r32,LatinOffset:int(data[5])<<8|int(data[6])}\n}\nfunc unpackCaseRanges(data []byte) []CaseRange {\nresult := make([]CaseRange,len(data)/20)\np:=0\nfor i := range result {\nresult[i] = CaseRange{")
	for field := 0; field < 5; field++ {
		if field > 0 {
			decoder.WriteByte(',')
		}
		if field == 2 {
			decoder.WriteString("d{")
		}
		if field >= 2 {
			decoder.WriteString("rune(")
		}
		for b := 0; b < 4; b++ {
			if b > 0 {
				decoder.WriteByte('|')
			}
			index := "p"
			if offset := field*4 + b; offset != 0 {
				index += "+" + strconv.Itoa(offset)
			}
			fmt.Fprintf(&decoder, "uint32(data[%s])", index)
			if shift := 24 - b*8; shift != 0 {
				fmt.Fprintf(&decoder, "<<%d", shift)
			}
		}
		if field >= 2 {
			decoder.WriteByte(')')
		}
	}
	decoder.WriteString("}}\np+=20\n}\nreturn result\n}\n")
	return append(data, decoder.String()...), resource, nil
}
