[package]
name = "mini-go-tooling"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = ["crates-io"]
description = "Compiler language tooling for Mini-Go"
readme = "README.md"
include = [
    "/src/**",
    "/assets/compiler.json.gz",
    "/README.md",
    "/LICENSE",
    "/LICENSE-Go",
]

[dependencies]
mini-go.workspace = true
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["raw_value"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
base64 = "0.22"
tokio = { version = "1", features = ["sync", "time", "rt", "macros", "io-util", "io-std", "fs"] }
