// Package runtimecheck produces language-neutral runtime verification inputs.
package runtimecheck

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"reflect"
	"sort"
	"strconv"
	"strings"
	"unicode"

	"github.com/d7z-team/mini-go/compiler/types"
	"github.com/d7z-team/mini-go/runtime/bytecode"
)

// Contract records the current wire identities and runtime-owned descriptors.
type Contract struct {
	CompilerID        string                         `json:"compiler_id"`
	ExecutionFormat   string                         `json:"execution_format"`
	ExecutionVersion  int                            `json:"execution_version"`
	ExecutionContract string                         `json:"execution_contract"`
	IntrinsicSchema   string                         `json:"intrinsic_schema"`
	Spec              bytecode.Spec                  `json:"spec"`
	Intrinsics        []bytecode.IntrinsicDescriptor `json:"intrinsics"`
	Costs             map[string]int                 `json:"costs"`
	BufferLayout      BufferLayout                   `json:"buffer_layout"`
}

// GenerateRustContract derives Rust wire declarations from the actual Go
// models. Sources are used to discover intrinsic IDs; their descriptors are
// obtained from the runtime contract rather than copied into this generator.
func GenerateRustContract(sources fs.FS) ([]byte, error) {
	data, err := fs.ReadFile(sources, "runtime/bytecode/intrinsic.go")
	if err != nil {
		return nil, err
	}
	file, err := parser.ParseFile(token.NewFileSet(), "intrinsic.go", data, 0)
	if err != nil {
		return nil, err
	}
	contract := Contract{
		CompilerID:      bytecode.CompilerIdentity,
		ExecutionFormat: bytecode.ExecutionFormat, ExecutionVersion: bytecode.ExecutionVersion,
		ExecutionContract: bytecode.ExecutionContract, IntrinsicSchema: bytecode.IntrinsicSchema,
		Spec:  bytecode.CurrentSpec(),
		Costs: map[string]int{"node": bytecode.RuntimeNodeBytes, "slot": bytecode.RuntimeSlotBytes, "map_entry": bytecode.RuntimeMapEntryBytes, "byte": bytecode.RuntimeByteBytes},
	}
	contract.BufferLayout, err = describeBufferLayout(sources)
	if err != nil {
		return nil, err
	}
	seen := map[bytecode.IntrinsicID]bool{}
	ast.Inspect(file, func(node ast.Node) bool {
		pair, ok := node.(*ast.KeyValueExpr)
		if !ok {
			return true
		}
		key, ok := pair.Key.(*ast.Ident)
		if !ok || key.Name != "ID" {
			return true
		}
		literal, ok := pair.Value.(*ast.BasicLit)
		if !ok || literal.Kind != token.STRING {
			return true
		}
		text, parseErr := strconv.Unquote(literal.Value)
		if parseErr != nil {
			err = parseErr
			return false
		}
		id := bytecode.IntrinsicID(text)
		descriptor, found := bytecode.Intrinsic(id)
		if !found || seen[id] {
			err = fmt.Errorf("intrinsic declaration %q is missing or duplicated", id)
			return false
		}
		seen[id] = true
		contract.Intrinsics = append(contract.Intrinsics, descriptor)
		return true
	})
	if err != nil {
		return nil, err
	}
	if len(contract.Intrinsics) == 0 {
		return nil, errors.New("no intrinsic declarations discovered")
	}
	sort.Slice(contract.Intrinsics, func(i, j int) bool { return contract.Intrinsics[i].ID < contract.Intrinsics[j].ID })
	var encoded bytes.Buffer
	encoder := json.NewEncoder(&encoded)
	encoder.SetEscapeHTML(false)
	if err := encoder.Encode(contract); err != nil {
		return nil, err
	}
	var out bytes.Buffer
	out.WriteString("// Code generated by mini-go-dev runtime-contract; DO NOT EDIT.\n")
	out.WriteString("use serde::Serialize;\nuse std::collections::BTreeMap;\n\n")
	fmt.Fprintf(&out, "pub const CONTRACT_JSON: &str = r###\"%s\"###;\n", bytes.TrimSpace(encoded.Bytes()))
	names := make([]string, len(contract.Intrinsics))
	out.WriteString("#[derive(Clone, Copy, Debug, PartialEq, Eq)]\npub enum Intrinsic {\n")
	for index, intrinsic := range contract.Intrinsics {
		var name strings.Builder
		for _, part := range strings.FieldsFunc(string(intrinsic.ID), func(r rune) bool { return r == '.' || r == '_' }) {
			name.WriteString(strings.ToUpper(part[:1]))
			name.WriteString(part[1:])
		}
		names[index] = name.String()
		fmt.Fprintf(&out, "    %s,\n", names[index])
	}
	out.WriteString("}\nimpl Intrinsic {\n    pub fn from_id(id: &str) -> Option<Self> { Some(match id {\n")
	for index, intrinsic := range contract.Intrinsics {
		fmt.Fprintf(&out, "        %q => Self::%s,\n", intrinsic.ID, names[index])
	}
	out.WriteString("        _ => return None,\n    }) }\n    pub fn id(self) -> &'static str { match self {\n")
	for index, intrinsic := range contract.Intrinsics {
		fmt.Fprintf(&out, "        Self::%s => %q,\n", names[index], intrinsic.ID)
	}
	out.WriteString("    } }\n    pub fn arity(self) -> (usize, usize) { match self {\n")
	for index, intrinsic := range contract.Intrinsics {
		fmt.Fprintf(&out, "        Self::%s => (%d, %d),\n", names[index], intrinsic.ArgCount, intrinsic.ResultCount)
	}
	out.WriteString("    } }\n    pub fn is_reflect(self) -> bool { matches!(self,\n")
	separator := ""
	for index, intrinsic := range contract.Intrinsics {
		if strings.HasPrefix(string(intrinsic.ID), "reflect.") {
			fmt.Fprintf(&out, "%sSelf::%s", separator, names[index])
			separator = " | "
		}
	}
	out.WriteString("\n    ) }\n}\n")
	models := []any{
		bytecode.ExecutionImage{},
		bytecode.Artifact{},
		bytecode.ProgramSymbols{},
		bytecode.ConstPayload{},
		bytecode.LocalPayload{},
		bytecode.UpvaluePayload{},
		bytecode.GlobalPayload{},
		bytecode.AddressPayload{},
		bytecode.TypePayload{},
		bytecode.OperatorPayload{},
		bytecode.MakeSequencePayload{},
		bytecode.MakeMapPayload{},
		bytecode.MakeStructPayload{},
		bytecode.MakeSlicePayload{},
		bytecode.MakeWaitablePayload{},
		bytecode.SelectPayload{},
		bytecode.SelectCase{},
		bytecode.CountPayload{},
		bytecode.FieldPayload{},
		bytecode.ExportPayload{},
		bytecode.InitModulePayload{},
		bytecode.LabelPayload{},
		bytecode.JumpPayload{},
		bytecode.CallPayload{},
		bytecode.CallInterfacePayload{},
		bytecode.ClosurePayload{},
		bytecode.ReturnPayload{},
		bytecode.DeferPayload{},
		bytecode.CallFFIPayload{},
		bytecode.CallIntrinsicPayload{},
	}
	g := rustModelGenerator{out: &out, models: map[reflect.Type]bool{}, names: map[string]reflect.Type{}}
	for _, model := range models {
		g.collect(reflect.TypeOf(model))
	}
	if g.err != nil {
		return nil, g.err
	}
	for _, model := range g.order {
		g.emit(model)
	}
	// Primitive and kind names are compiler-owned; derive the complete numeric
	// groups from their iota declarations, failing if that representation changes.
	model, err := fs.ReadFile(sources, "compiler/types/model.go")
	if err != nil {
		return nil, err
	}
	parsed, err := parser.ParseFile(token.NewFileSet(), "model.go", model, 0)
	if err != nil {
		return nil, err
	}
	for _, declaration := range parsed.Decls {
		group, ok := declaration.(*ast.GenDecl)
		if !ok || group.Tok != token.CONST {
			continue
		}
		first := group.Specs[0].(*ast.ValueSpec)
		name, ok := first.Type.(*ast.Ident)
		if !ok || (name.Name != "Kind" && name.Name != "PrimitiveKind" && name.Name != "ChannelDir") {
			continue
		}
		for ordinal, spec := range group.Specs {
			value := spec.(*ast.ValueSpec)
			if len(value.Names) != 1 || (ordinal > 0 && len(value.Values) != 0) {
				return nil, fmt.Errorf("unsupported enum declaration %s", name.Name)
			}
			if ordinal == 0 {
				if len(value.Values) != 1 {
					return nil, fmt.Errorf("missing iota: %s", name.Name)
				}
				if ident, ok := value.Values[0].(*ast.Ident); !ok || ident.Name != "iota" {
					return nil, fmt.Errorf("expected iota: %s", name.Name)
				}
			}
			fmt.Fprintf(&out, "#[allow(non_upper_case_globals)]\npub const %s: u8 = %d;\n", value.Names[0].Name, ordinal)
		}
	}
	return out.Bytes(), g.err
}

type rustModelGenerator struct {
	out    *bytes.Buffer
	models map[reflect.Type]bool
	names  map[string]reflect.Type
	order  []reflect.Type
	err    error
}

func (g *rustModelGenerator) collect(t reflect.Type) {
	if t == reflect.TypeFor[json.RawMessage]() {
		return
	}
	switch t.Kind() {
	case reflect.Pointer, reflect.Slice, reflect.Array, reflect.Map:
		g.collect(t.Elem())
	case reflect.Struct:
		if g.models[t] {
			return
		}
		if prior, ok := g.names[t.Name()]; ok && prior != t {
			g.err = fmt.Errorf("Rust model name collision: %v and %v", prior, t)
			return
		}
		g.models[t], g.names[t.Name()] = true, t
		g.order = append(g.order, t)
		for i := range t.NumField() {
			field := t.Field(i)
			if field.IsExported() && field.Tag.Get("json") != "-" {
				g.collect(field.Type)
			}
		}
	}
}

func (g *rustModelGenerator) rustType(t reflect.Type) string {
	if t == reflect.TypeFor[json.RawMessage]() {
		return "Option<Box<serde_json::value::RawValue>>"
	}
	if t == reflect.TypeFor[[]byte]() {
		g.err = fmt.Errorf("byte field requires an explicit wire codec: %v", t)
		return "()"
	}
	switch t.Kind() {
	case reflect.Struct:
		return t.Name()
	case reflect.Pointer:
		return "Option<Box<" + g.rustType(t.Elem()) + ">>"
	case reflect.Slice:
		return "crate::contract::GoSlice<" + g.rustType(t.Elem()) + ">"
	case reflect.Map:
		if t.Key().Kind() != reflect.String {
			g.err = fmt.Errorf("non-string map key: %v", t)
		}
		return "Option<BTreeMap<String, " + g.rustType(t.Elem()) + ">>"
	case reflect.String:
		return "String"
	case reflect.Bool:
		return "bool"
	case reflect.Int, reflect.Int64:
		return "i64"
	case reflect.Uint8:
		return "u8"
	case reflect.Uint64:
		return "u64"
	default:
		g.err = fmt.Errorf("unsupported contract field: %v", t)
		return "()"
	}
}

func (g *rustModelGenerator) emit(t reflect.Type) {
	derive := "Clone, Debug, Default, Serialize"
	if t == reflect.TypeFor[types.TypeRef]() || t == reflect.TypeFor[types.TypeKey]() {
		derive += ", PartialEq, Eq, Hash"
	}
	fmt.Fprintf(g.out, "\n#[derive(%s)]\n#[serde(default, deny_unknown_fields)]\npub struct %s {\n", derive, t.Name())
	var decoding strings.Builder
	for i := range t.NumField() {
		field := t.Field(i)
		if !field.IsExported() || field.Tag.Get("json") == "-" {
			continue
		}
		parts := strings.Split(field.Tag.Get("json"), ",")
		name := parts[0]
		if name == "" {
			name = field.Name
		}
		attribute := fmt.Sprintf("rename = %q", name)
		if len(parts) > 1 && parts[1] == "omitempty" {
			skip := ""
			switch field.Type.Kind() {
			case reflect.Pointer:
				skip = "Option::is_none"
			case reflect.Slice:
				skip = "crate::contract::GoSlice::is_empty"
			case reflect.Map:
				skip = "crate::contract::map_is_empty"
			case reflect.String:
				skip = "String::is_empty"
			case reflect.Bool, reflect.Int, reflect.Int64, reflect.Uint8, reflect.Uint64:
				skip = "crate::contract::is_default"
			}
			if field.Type == reflect.TypeFor[json.RawMessage]() {
				skip = "Option::is_none"
			}
			if skip != "" {
				attribute += fmt.Sprintf(", skip_serializing_if = %q", skip)
			}
		}
		var identifier strings.Builder
		runes := []rune(name)
		for index, char := range runes {
			if unicode.IsUpper(char) && index > 0 && (unicode.IsLower(runes[index-1]) || unicode.IsDigit(runes[index-1]) || unicode.IsUpper(runes[index-1]) && index+1 < len(runes) && unicode.IsLower(runes[index+1])) {
				identifier.WriteByte('_')
			}
			identifier.WriteRune(unicode.ToLower(char))
		}
		fmt.Fprintf(g.out, "    #[serde(%s)]\n    pub r#%s: %s,\n", attribute, identifier.String(), g.rustType(field.Type))
		kind := "scalar"
		switch field.Type.Kind() {
		case reflect.Struct:
			kind = "object"
		case reflect.Map:
			kind = "map"
		case reflect.Pointer:
			kind = "value"
			if field.Type.Elem().Kind() == reflect.Struct {
				kind = "pointer"
			}
		case reflect.Slice:
			kind = "value"
		}
		if field.Type == reflect.TypeFor[json.RawMessage]() {
			kind = "raw"
		}
		fmt.Fprintf(&decoding, "    r#%s: %q => %s,\n", identifier.String(), name, kind)
	}
	g.out.WriteString("}\n")
	fmt.Fprintf(g.out, "crate::contract::go_object!(%s {\n%s});\n", t.Name(), decoding.String())
}
