// Code generated by mini-go-dev compiler-binary; DO NOT EDIT.
package ast

import (
	"github.com/d7z-team/mini-go/compiler/identity"
	compiler_source "github.com/d7z-team/mini-go/compiler/source"
)

// EncodeIdentityBlockStmt writes the compiler identity schema fields.
func EncodeIdentityBlockStmt(w *identity.Writer, value BlockStmt) {
	if !w.EnterStructure() {
		return
	}
	w.Uint(uint64(value.NodeID))
	compiler_source.EncodeIdentitySpan(w, value.Span)
	w.Uint(uint64(len(value.Stmts)))
	for i0 := range value.Stmts {
		EncodeIdentityStatement(w, value.Stmts[i0])
	}
	w.LeaveStructure()
}

// EncodeIdentityCaseClause writes the compiler identity schema fields.
func EncodeIdentityCaseClause(w *identity.Writer, value CaseClause) {
	if !w.EnterStructure() {
		return
	}
	w.Uint(uint64(value.NodeID))
	compiler_source.EncodeIdentitySpan(w, value.Span)
	w.Uint(uint64(len(value.Values)))
	for i0 := range value.Values {
		EncodeIdentityExpression(w, value.Values[i0])
	}
	w.Uint(uint64(len(value.Types)))
	for i0 := range value.Types {
		EncodeIdentityTypeExpr(w, value.Types[i0])
	}
	w.Bool(bool(value.Nil))
	w.Bool(value.Comm != nil)
	if value.Comm != nil {
		EncodeIdentityStatement(w, (*value.Comm))
	}
	EncodeIdentityBlockStmt(w, value.Body)
	w.Bool(bool(value.Default))
	w.LeaveStructure()
}

// EncodeIdentityDecl writes the compiler identity schema fields.
func EncodeIdentityDecl(w *identity.Writer, value Decl) {
	if !w.EnterStructure() {
		return
	}
	w.Uint(uint64(value.NodeID))
	w.String(string(value.Kind))
	compiler_source.EncodeIdentitySpan(w, value.Span)
	w.Bool(value.Import != nil)
	if value.Import != nil {
		EncodeIdentityImportDecl(w, (*value.Import))
	}
	w.Bool(value.Const != nil)
	if value.Const != nil {
		EncodeIdentityValueDecl(w, (*value.Const))
	}
	w.Bool(value.Var != nil)
	if value.Var != nil {
		EncodeIdentityValueDecl(w, (*value.Var))
	}
	w.Bool(value.Type != nil)
	if value.Type != nil {
		EncodeIdentityTypeDecl(w, (*value.Type))
	}
	w.Bool(value.Func != nil)
	if value.Func != nil {
		EncodeIdentityFuncDecl(w, (*value.Func))
	}
	w.LeaveStructure()
}

// EncodeIdentityEmbedFile writes the compiler identity schema fields.
func EncodeIdentityEmbedFile(w *identity.Writer, value EmbedFile) {
	if !w.EnterStructure() {
		return
	}
	w.String(string(value.Path))
	w.Bool(value.Data != nil)
	w.Bytes(value.Data)
	w.LeaveStructure()
}

// EncodeIdentityExpression writes the compiler identity schema fields.
func EncodeIdentityExpression(w *identity.Writer, value Expression) {
	if !w.EnterStructure() {
		return
	}
	w.Uint(uint64(value.NodeID))
	w.String(string(value.Kind))
	compiler_source.EncodeIdentitySpan(w, value.Span)
	w.String(string(value.Name))
	EncodeIdentityIdentifier(w, value.NameID)
	w.String(string(value.Literal))
	w.Bool(value.Type != nil)
	if value.Type != nil {
		EncodeIdentityTypeExpr(w, (*value.Type))
	}
	w.Bool(bool(value.TypeSwitch))
	w.String(string(value.Operator))
	w.Bool(value.Left != nil)
	if value.Left != nil {
		EncodeIdentityExpression(w, (*value.Left))
	}
	w.Bool(value.Right != nil)
	if value.Right != nil {
		EncodeIdentityExpression(w, (*value.Right))
	}
	w.Bool(value.Operand != nil)
	if value.Operand != nil {
		EncodeIdentityExpression(w, (*value.Operand))
	}
	w.Bool(value.Callee != nil)
	if value.Callee != nil {
		EncodeIdentityExpression(w, (*value.Callee))
	}
	w.Uint(uint64(len(value.Args)))
	for i0 := range value.Args {
		EncodeIdentityExpression(w, value.Args[i0])
	}
	w.Bool(bool(value.Ellipsis))
	w.String(string(value.Field))
	w.Bool(value.Index != nil)
	if value.Index != nil {
		EncodeIdentityExpression(w, (*value.Index))
	}
	w.Bool(value.Start != nil)
	if value.Start != nil {
		EncodeIdentityExpression(w, (*value.Start))
	}
	w.Bool(value.End != nil)
	if value.End != nil {
		EncodeIdentityExpression(w, (*value.End))
	}
	w.Bool(value.Max != nil)
	if value.Max != nil {
		EncodeIdentityExpression(w, (*value.Max))
	}
	w.Uint(uint64(len(value.Items)))
	for i0 := range value.Items {
		EncodeIdentityKeyValue(w, value.Items[i0])
	}
	w.Uint(uint64(len(value.EmbedFiles)))
	for i0 := range value.EmbedFiles {
		EncodeIdentityEmbedFile(w, value.EmbedFiles[i0])
	}
	w.Bool(value.Func != nil)
	if value.Func != nil {
		EncodeIdentityFuncDecl(w, (*value.Func))
	}
	w.LeaveStructure()
}

// EncodeIdentityField writes the compiler identity schema fields.
func EncodeIdentityField(w *identity.Writer, value Field) {
	if !w.EnterStructure() {
		return
	}
	w.Uint(uint64(value.NodeID))
	w.String(string(value.Name))
	EncodeIdentityIdentifier(w, value.NameID)
	EncodeIdentityTypeExpr(w, value.Type)
	w.String(string(value.Tag))
	w.Bool(bool(value.Variadic))
	compiler_source.EncodeIdentitySpan(w, value.Span)
	w.LeaveStructure()
}

// EncodeIdentityFuncDecl writes the compiler identity schema fields.
func EncodeIdentityFuncDecl(w *identity.Writer, value FuncDecl) {
	if !w.EnterStructure() {
		return
	}
	w.Uint(uint64(value.NodeID))
	w.String(string(value.Name))
	EncodeIdentityIdentifier(w, value.NameID)
	w.Bool(value.Receiver != nil)
	if value.Receiver != nil {
		EncodeIdentityField(w, (*value.Receiver))
	}
	w.Uint(uint64(len(value.TypeParams)))
	for i0 := range value.TypeParams {
		EncodeIdentityTypeParam(w, value.TypeParams[i0])
	}
	w.Uint(uint64(len(value.Params)))
	for i0 := range value.Params {
		EncodeIdentityField(w, value.Params[i0])
	}
	w.Uint(uint64(len(value.Results)))
	for i0 := range value.Results {
		EncodeIdentityField(w, value.Results[i0])
	}
	EncodeIdentityBlockStmt(w, value.Body)
	w.Bool(bool(value.Template))
	w.LeaveStructure()
}

// EncodeIdentityIdentifier writes the compiler identity schema fields.
func EncodeIdentityIdentifier(w *identity.Writer, value Identifier) {
	if !w.EnterStructure() {
		return
	}
	w.Uint(uint64(value.ID))
	w.String(string(value.Text))
	compiler_source.EncodeIdentitySpan(w, value.Span)
	w.LeaveStructure()
}

// EncodeIdentityImportDecl writes the compiler identity schema fields.
func EncodeIdentityImportDecl(w *identity.Writer, value ImportDecl) {
	if !w.EnterStructure() {
		return
	}
	w.String(string(value.Path))
	compiler_source.EncodeIdentitySpan(w, value.PathSpan)
	w.String(string(value.Alias))
	EncodeIdentityIdentifier(w, value.AliasID)
	w.LeaveStructure()
}

// EncodeIdentityKeyValue writes the compiler identity schema fields.
func EncodeIdentityKeyValue(w *identity.Writer, value KeyValue) {
	if !w.EnterStructure() {
		return
	}
	w.Uint(uint64(value.NodeID))
	w.Bool(value.Key != nil)
	if value.Key != nil {
		EncodeIdentityExpression(w, (*value.Key))
	}
	EncodeIdentityExpression(w, value.Value)
	w.LeaveStructure()
}

// EncodeIdentityStatement writes the compiler identity schema fields.
func EncodeIdentityStatement(w *identity.Writer, value Statement) {
	if !w.EnterStructure() {
		return
	}
	w.Uint(uint64(value.NodeID))
	w.String(string(value.Kind))
	compiler_source.EncodeIdentitySpan(w, value.Span)
	w.Uint(uint64(len(value.Decls)))
	for i0 := range value.Decls {
		EncodeIdentityDecl(w, value.Decls[i0])
	}
	w.Bool(value.Expr != nil)
	if value.Expr != nil {
		EncodeIdentityExpression(w, (*value.Expr))
	}
	w.Uint(uint64(len(value.Left)))
	for i0 := range value.Left {
		EncodeIdentityExpression(w, value.Left[i0])
	}
	w.Uint(uint64(len(value.Right)))
	for i0 := range value.Right {
		EncodeIdentityExpression(w, value.Right[i0])
	}
	w.String(string(value.Op))
	EncodeIdentityBlockStmt(w, value.Body)
	w.Bool(value.Init != nil)
	if value.Init != nil {
		EncodeIdentityStatement(w, (*value.Init))
	}
	w.Bool(value.Cond != nil)
	if value.Cond != nil {
		EncodeIdentityExpression(w, (*value.Cond))
	}
	w.Bool(value.Post != nil)
	if value.Post != nil {
		EncodeIdentityStatement(w, (*value.Post))
	}
	w.Bool(value.Else != nil)
	if value.Else != nil {
		EncodeIdentityStatement(w, (*value.Else))
	}
	w.Bool(value.Key != nil)
	if value.Key != nil {
		EncodeIdentityExpression(w, (*value.Key))
	}
	w.Bool(value.Value != nil)
	if value.Value != nil {
		EncodeIdentityExpression(w, (*value.Value))
	}
	w.Bool(value.Range != nil)
	if value.Range != nil {
		EncodeIdentityExpression(w, (*value.Range))
	}
	w.Uint(uint64(len(value.Cases)))
	for i0 := range value.Cases {
		EncodeIdentityCaseClause(w, value.Cases[i0])
	}
	w.String(string(value.Label))
	EncodeIdentityIdentifier(w, value.LabelID)
	w.Uint(uint64(len(value.Results)))
	for i0 := range value.Results {
		EncodeIdentityExpression(w, value.Results[i0])
	}
	w.Bool(bool(value.TypeSwitch))
	w.String(string(value.TypeSwitchName))
	EncodeIdentityIdentifier(w, value.TypeSwitchID)
	w.LeaveStructure()
}

// EncodeIdentityTypeDecl writes the compiler identity schema fields.
func EncodeIdentityTypeDecl(w *identity.Writer, value TypeDecl) {
	if !w.EnterStructure() {
		return
	}
	w.String(string(value.Name))
	EncodeIdentityIdentifier(w, value.NameID)
	w.Uint(uint64(len(value.TypeParams)))
	for i0 := range value.TypeParams {
		EncodeIdentityTypeParam(w, value.TypeParams[i0])
	}
	EncodeIdentityTypeExpr(w, value.Type)
	w.Bool(bool(value.Alias))
	w.LeaveStructure()
}

// EncodeIdentityTypeExpr writes the compiler identity schema fields.
func EncodeIdentityTypeExpr(w *identity.Writer, value TypeExpr) {
	if !w.EnterStructure() {
		return
	}
	w.Uint(uint64(value.NodeID))
	w.String(string(value.Kind))
	w.String(string(value.Name))
	EncodeIdentityIdentifier(w, value.NameID)
	EncodeIdentityIdentifier(w, value.QualifierID)
	w.Bool(value.Elem != nil)
	if value.Elem != nil {
		EncodeIdentityTypeExpr(w, (*value.Elem))
	}
	w.Bool(value.Key != nil)
	if value.Key != nil {
		EncodeIdentityTypeExpr(w, (*value.Key))
	}
	w.Bool(value.Len != nil)
	if value.Len != nil {
		EncodeIdentityExpression(w, (*value.Len))
	}
	w.Bool(bool(value.LenInfer))
	w.Uint(uint64(len(value.Params)))
	for i0 := range value.Params {
		EncodeIdentityField(w, value.Params[i0])
	}
	w.Uint(uint64(len(value.Results)))
	for i0 := range value.Results {
		EncodeIdentityField(w, value.Results[i0])
	}
	w.Uint(uint64(len(value.Fields)))
	for i0 := range value.Fields {
		EncodeIdentityField(w, value.Fields[i0])
	}
	w.Uint(uint64(len(value.Methods)))
	for i0 := range value.Methods {
		EncodeIdentityFuncDecl(w, value.Methods[i0])
	}
	w.Uint(uint64(len(value.Embeds)))
	for i0 := range value.Embeds {
		EncodeIdentityTypeExpr(w, value.Embeds[i0])
	}
	w.Uint(uint64(len(value.Terms)))
	for i0 := range value.Terms {
		EncodeIdentityTypeTerm(w, value.Terms[i0])
	}
	w.String(string(value.Direction))
	w.Bool(value.Base != nil)
	if value.Base != nil {
		EncodeIdentityTypeExpr(w, (*value.Base))
	}
	w.Uint(uint64(len(value.TypeArgs)))
	for i0 := range value.TypeArgs {
		EncodeIdentityTypeExpr(w, value.TypeArgs[i0])
	}
	compiler_source.EncodeIdentitySpan(w, value.Span)
	w.LeaveStructure()
}

// EncodeIdentityTypeParam writes the compiler identity schema fields.
func EncodeIdentityTypeParam(w *identity.Writer, value TypeParam) {
	if !w.EnterStructure() {
		return
	}
	w.Uint(uint64(value.NodeID))
	w.String(string(value.Name))
	EncodeIdentityIdentifier(w, value.NameID)
	EncodeIdentityTypeExpr(w, value.Constraint)
	compiler_source.EncodeIdentitySpan(w, value.Span)
	w.LeaveStructure()
}

// EncodeIdentityTypeTerm writes the compiler identity schema fields.
func EncodeIdentityTypeTerm(w *identity.Writer, value TypeTerm) {
	if !w.EnterStructure() {
		return
	}
	w.Uint(uint64(value.NodeID))
	EncodeIdentityTypeExpr(w, value.Type)
	w.Bool(bool(value.Approx))
	compiler_source.EncodeIdentitySpan(w, value.Span)
	w.LeaveStructure()
}

// EncodeIdentityValueDecl writes the compiler identity schema fields.
func EncodeIdentityValueDecl(w *identity.Writer, value ValueDecl) {
	if !w.EnterStructure() {
		return
	}
	w.Uint(uint64(len(value.Names)))
	for i0 := range value.Names {
		w.String(string(value.Names[i0]))
	}
	w.Uint(uint64(len(value.NameIDs)))
	for i0 := range value.NameIDs {
		EncodeIdentityIdentifier(w, value.NameIDs[i0])
	}
	EncodeIdentityTypeExpr(w, value.Type)
	w.Uint(uint64(len(value.Values)))
	for i0 := range value.Values {
		EncodeIdentityExpression(w, value.Values[i0])
	}
	w.Uint(uint64(len(value.EmbedPatterns)))
	for i0 := range value.EmbedPatterns {
		w.String(string(value.EmbedPatterns[i0]))
	}
	w.LeaveStructure()
}
