// Code generated by mini-go-dev bytecode-json; DO NOT EDIT.
package bytecode

import "fmt"

type DescriptorTables struct {
	Const         []ConstPayload         `json:"const,omitempty"`
	Local         []LocalPayload         `json:"local,omitempty"`
	Upvalue       []UpvaluePayload       `json:"upvalue,omitempty"`
	Global        []GlobalPayload        `json:"global,omitempty"`
	Address       []AddressPayload       `json:"address,omitempty"`
	Type          []TypePayload          `json:"type,omitempty"`
	Operator      []OperatorPayload      `json:"operator,omitempty"`
	MakeSequence  []MakeSequencePayload  `json:"makesequence,omitempty"`
	MakeMap       []MakeMapPayload       `json:"makemap,omitempty"`
	MakeStruct    []MakeStructPayload    `json:"makestruct,omitempty"`
	MakeSlice     []MakeSlicePayload     `json:"makeslice,omitempty"`
	MakeWaitable  []MakeWaitablePayload  `json:"makewaitable,omitempty"`
	Select        []SelectPayload        `json:"select,omitempty"`
	Count         []CountPayload         `json:"count,omitempty"`
	Field         []FieldPayload         `json:"field,omitempty"`
	Export        []ExportPayload        `json:"export,omitempty"`
	InitModule    []InitModulePayload    `json:"initmodule,omitempty"`
	Label         []LabelPayload         `json:"label,omitempty"`
	Jump          []JumpPayload          `json:"jump,omitempty"`
	Call          []CallPayload          `json:"call,omitempty"`
	CallInterface []CallInterfacePayload `json:"callinterface,omitempty"`
	Closure       []ClosurePayload       `json:"closure,omitempty"`
	Return        []ReturnPayload        `json:"return,omitempty"`
	Defer         []DeferPayload         `json:"defer,omitempty"`
	CallFFI       []CallFFIPayload       `json:"callffi,omitempty"`
	CallIntrinsic []CallIntrinsicPayload `json:"callintrinsic,omitempty"`
	TypeDispatch  []TypeDispatchPayload  `json:"typedispatch,omitempty"`
	CompareBranch []CompareBranchPayload `json:"comparebranch,omitempty"`
	FieldPath     []FieldPathPayload     `json:"fieldpath,omitempty"`
}

func (t *DescriptorTables) Append(value Payload) (uint32, error) {
	switch v := value.(type) {
	case nil:
		return 0, nil
	case ConstPayload:
		if uint64(len(t.Const)) >= 1<<32 {
			return 0, fmt.Errorf("descriptor table exceeds uint32")
		}
		index := uint32(len(t.Const))
		t.Const = append(t.Const, v)
		return index, nil
	case LocalPayload:
		if uint64(len(t.Local)) >= 1<<32 {
			return 0, fmt.Errorf("descriptor table exceeds uint32")
		}
		index := uint32(len(t.Local))
		t.Local = append(t.Local, v)
		return index, nil
	case UpvaluePayload:
		if uint64(len(t.Upvalue)) >= 1<<32 {
			return 0, fmt.Errorf("descriptor table exceeds uint32")
		}
		index := uint32(len(t.Upvalue))
		t.Upvalue = append(t.Upvalue, v)
		return index, nil
	case GlobalPayload:
		if uint64(len(t.Global)) >= 1<<32 {
			return 0, fmt.Errorf("descriptor table exceeds uint32")
		}
		index := uint32(len(t.Global))
		t.Global = append(t.Global, v)
		return index, nil
	case AddressPayload:
		if uint64(len(t.Address)) >= 1<<32 {
			return 0, fmt.Errorf("descriptor table exceeds uint32")
		}
		index := uint32(len(t.Address))
		t.Address = append(t.Address, v)
		return index, nil
	case TypePayload:
		if uint64(len(t.Type)) >= 1<<32 {
			return 0, fmt.Errorf("descriptor table exceeds uint32")
		}
		index := uint32(len(t.Type))
		t.Type = append(t.Type, v)
		return index, nil
	case OperatorPayload:
		if uint64(len(t.Operator)) >= 1<<32 {
			return 0, fmt.Errorf("descriptor table exceeds uint32")
		}
		index := uint32(len(t.Operator))
		t.Operator = append(t.Operator, v)
		return index, nil
	case MakeSequencePayload:
		if uint64(len(t.MakeSequence)) >= 1<<32 {
			return 0, fmt.Errorf("descriptor table exceeds uint32")
		}
		index := uint32(len(t.MakeSequence))
		t.MakeSequence = append(t.MakeSequence, v)
		return index, nil
	case MakeMapPayload:
		if uint64(len(t.MakeMap)) >= 1<<32 {
			return 0, fmt.Errorf("descriptor table exceeds uint32")
		}
		index := uint32(len(t.MakeMap))
		t.MakeMap = append(t.MakeMap, v)
		return index, nil
	case MakeStructPayload:
		if uint64(len(t.MakeStruct)) >= 1<<32 {
			return 0, fmt.Errorf("descriptor table exceeds uint32")
		}
		index := uint32(len(t.MakeStruct))
		t.MakeStruct = append(t.MakeStruct, v)
		return index, nil
	case MakeSlicePayload:
		if uint64(len(t.MakeSlice)) >= 1<<32 {
			return 0, fmt.Errorf("descriptor table exceeds uint32")
		}
		index := uint32(len(t.MakeSlice))
		t.MakeSlice = append(t.MakeSlice, v)
		return index, nil
	case MakeWaitablePayload:
		if uint64(len(t.MakeWaitable)) >= 1<<32 {
			return 0, fmt.Errorf("descriptor table exceeds uint32")
		}
		index := uint32(len(t.MakeWaitable))
		t.MakeWaitable = append(t.MakeWaitable, v)
		return index, nil
	case SelectPayload:
		if uint64(len(t.Select)) >= 1<<32 {
			return 0, fmt.Errorf("descriptor table exceeds uint32")
		}
		index := uint32(len(t.Select))
		t.Select = append(t.Select, v)
		return index, nil
	case CountPayload:
		if uint64(len(t.Count)) >= 1<<32 {
			return 0, fmt.Errorf("descriptor table exceeds uint32")
		}
		index := uint32(len(t.Count))
		t.Count = append(t.Count, v)
		return index, nil
	case FieldPayload:
		if uint64(len(t.Field)) >= 1<<32 {
			return 0, fmt.Errorf("descriptor table exceeds uint32")
		}
		index := uint32(len(t.Field))
		t.Field = append(t.Field, v)
		return index, nil
	case ExportPayload:
		if uint64(len(t.Export)) >= 1<<32 {
			return 0, fmt.Errorf("descriptor table exceeds uint32")
		}
		index := uint32(len(t.Export))
		t.Export = append(t.Export, v)
		return index, nil
	case InitModulePayload:
		if uint64(len(t.InitModule)) >= 1<<32 {
			return 0, fmt.Errorf("descriptor table exceeds uint32")
		}
		index := uint32(len(t.InitModule))
		t.InitModule = append(t.InitModule, v)
		return index, nil
	case LabelPayload:
		if uint64(len(t.Label)) >= 1<<32 {
			return 0, fmt.Errorf("descriptor table exceeds uint32")
		}
		index := uint32(len(t.Label))
		t.Label = append(t.Label, v)
		return index, nil
	case JumpPayload:
		if uint64(len(t.Jump)) >= 1<<32 {
			return 0, fmt.Errorf("descriptor table exceeds uint32")
		}
		index := uint32(len(t.Jump))
		t.Jump = append(t.Jump, v)
		return index, nil
	case CallPayload:
		if uint64(len(t.Call)) >= 1<<32 {
			return 0, fmt.Errorf("descriptor table exceeds uint32")
		}
		index := uint32(len(t.Call))
		t.Call = append(t.Call, v)
		return index, nil
	case CallInterfacePayload:
		if uint64(len(t.CallInterface)) >= 1<<32 {
			return 0, fmt.Errorf("descriptor table exceeds uint32")
		}
		index := uint32(len(t.CallInterface))
		t.CallInterface = append(t.CallInterface, v)
		return index, nil
	case ClosurePayload:
		if uint64(len(t.Closure)) >= 1<<32 {
			return 0, fmt.Errorf("descriptor table exceeds uint32")
		}
		index := uint32(len(t.Closure))
		t.Closure = append(t.Closure, v)
		return index, nil
	case ReturnPayload:
		if uint64(len(t.Return)) >= 1<<32 {
			return 0, fmt.Errorf("descriptor table exceeds uint32")
		}
		index := uint32(len(t.Return))
		t.Return = append(t.Return, v)
		return index, nil
	case DeferPayload:
		if uint64(len(t.Defer)) >= 1<<32 {
			return 0, fmt.Errorf("descriptor table exceeds uint32")
		}
		index := uint32(len(t.Defer))
		t.Defer = append(t.Defer, v)
		return index, nil
	case CallFFIPayload:
		if uint64(len(t.CallFFI)) >= 1<<32 {
			return 0, fmt.Errorf("descriptor table exceeds uint32")
		}
		index := uint32(len(t.CallFFI))
		t.CallFFI = append(t.CallFFI, v)
		return index, nil
	case CallIntrinsicPayload:
		if uint64(len(t.CallIntrinsic)) >= 1<<32 {
			return 0, fmt.Errorf("descriptor table exceeds uint32")
		}
		index := uint32(len(t.CallIntrinsic))
		t.CallIntrinsic = append(t.CallIntrinsic, v)
		return index, nil
	case TypeDispatchPayload:
		if uint64(len(t.TypeDispatch)) >= 1<<32 {
			return 0, fmt.Errorf("descriptor table exceeds uint32")
		}
		index := uint32(len(t.TypeDispatch))
		t.TypeDispatch = append(t.TypeDispatch, v)
		return index, nil
	case CompareBranchPayload:
		if uint64(len(t.CompareBranch)) >= 1<<32 {
			return 0, fmt.Errorf("descriptor table exceeds uint32")
		}
		index := uint32(len(t.CompareBranch))
		t.CompareBranch = append(t.CompareBranch, v)
		return index, nil
	case FieldPathPayload:
		if uint64(len(t.FieldPath)) >= 1<<32 {
			return 0, fmt.Errorf("descriptor table exceeds uint32")
		}
		index := uint32(len(t.FieldPath))
		t.FieldPath = append(t.FieldPath, v)
		return index, nil
	}
	return 0, fmt.Errorf("unsupported descriptor %T", value)
}
func (t *DescriptorTables) Payload(op Opcode, index uint32) (Payload, error) {
	switch op {
	case Opcode(1):
		if uint64(index) < uint64(len(t.TypeDispatch)) {
			return t.TypeDispatch[index], nil
		}
	case Opcode(2):
		if uint64(index) < uint64(len(t.Select)) {
			return t.Select[index], nil
		}
	case Opcode(3):
		if uint64(index) < uint64(len(t.Const)) {
			return t.Const[index], nil
		}
	case Opcode(4):
		if uint64(index) < uint64(len(t.Type)) {
			return t.Type[index], nil
		}
	case Opcode(5):
		if index == 0 {
			return nil, nil
		}
	case Opcode(6):
		if uint64(index) < uint64(len(t.Operator)) {
			return t.Operator[index], nil
		}
	case Opcode(7):
		if uint64(index) < uint64(len(t.Operator)) {
			return t.Operator[index], nil
		}
	case Opcode(8):
		if uint64(index) < uint64(len(t.Local)) {
			return t.Local[index], nil
		}
	case Opcode(9):
		if uint64(index) < uint64(len(t.Local)) {
			return t.Local[index], nil
		}
	case Opcode(10):
		if uint64(index) < uint64(len(t.Upvalue)) {
			return t.Upvalue[index], nil
		}
	case Opcode(11):
		if uint64(index) < uint64(len(t.Upvalue)) {
			return t.Upvalue[index], nil
		}
	case Opcode(12):
		if uint64(index) < uint64(len(t.Global)) {
			return t.Global[index], nil
		}
	case Opcode(13):
		if uint64(index) < uint64(len(t.Global)) {
			return t.Global[index], nil
		}
	case Opcode(14):
		if uint64(index) < uint64(len(t.Label)) {
			return t.Label[index], nil
		}
	case Opcode(15):
		if uint64(index) < uint64(len(t.Jump)) {
			return t.Jump[index], nil
		}
	case Opcode(16):
		if uint64(index) < uint64(len(t.Jump)) {
			return t.Jump[index], nil
		}
	case Opcode(17):
		if uint64(index) < uint64(len(t.Return)) {
			return t.Return[index], nil
		}
	case Opcode(18):
		if index == 0 {
			return nil, nil
		}
	case Opcode(19):
		if index == 0 {
			return nil, nil
		}
	case Opcode(20):
		if uint64(index) < uint64(len(t.Defer)) {
			return t.Defer[index], nil
		}
	case Opcode(21):
		if uint64(index) < uint64(len(t.Call)) {
			return t.Call[index], nil
		}
	case Opcode(22):
		if uint64(index) < uint64(len(t.Call)) {
			return t.Call[index], nil
		}
	case Opcode(23):
		if uint64(index) < uint64(len(t.Call)) {
			return t.Call[index], nil
		}
	case Opcode(24):
		if uint64(index) < uint64(len(t.CallInterface)) {
			return t.CallInterface[index], nil
		}
	case Opcode(25):
		if uint64(index) < uint64(len(t.Closure)) {
			return t.Closure[index], nil
		}
	case Opcode(26):
		if uint64(index) < uint64(len(t.MakeSequence)) {
			return t.MakeSequence[index], nil
		}
	case Opcode(27):
		if uint64(index) < uint64(len(t.MakeMap)) {
			return t.MakeMap[index], nil
		}
	case Opcode(28):
		if uint64(index) < uint64(len(t.MakeStruct)) {
			return t.MakeStruct[index], nil
		}
	case Opcode(29):
		if uint64(index) < uint64(len(t.MakeSlice)) {
			return t.MakeSlice[index], nil
		}
	case Opcode(30):
		if uint64(index) < uint64(len(t.MakeWaitable)) {
			return t.MakeWaitable[index], nil
		}
	case Opcode(31):
		if index == 0 {
			return nil, nil
		}
	case Opcode(32):
		if index == 0 {
			return nil, nil
		}
	case Opcode(33):
		if index == 0 {
			return nil, nil
		}
	case Opcode(34):
		if index == 0 {
			return nil, nil
		}
	case Opcode(35):
		if index == 0 {
			return nil, nil
		}
	case Opcode(36):
		if index == 0 {
			return nil, nil
		}
	case Opcode(37):
		if index == 0 {
			return nil, nil
		}
	case Opcode(38):
		if uint64(index) < uint64(len(t.Count)) {
			return t.Count[index], nil
		}
	case Opcode(39):
		if index == 0 {
			return nil, nil
		}
	case Opcode(40):
		if index == 0 {
			return nil, nil
		}
	case Opcode(41):
		if index == 0 {
			return nil, nil
		}
	case Opcode(42):
		if index == 0 {
			return nil, nil
		}
	case Opcode(43):
		if uint64(index) < uint64(len(t.Local)) {
			return t.Local[index], nil
		}
	case Opcode(44):
		if uint64(index) < uint64(len(t.Local)) {
			return t.Local[index], nil
		}
	case Opcode(45):
		if uint64(index) < uint64(len(t.Local)) {
			return t.Local[index], nil
		}
	case Opcode(46):
		if uint64(index) < uint64(len(t.Field)) {
			return t.Field[index], nil
		}
	case Opcode(47):
		if index == 0 {
			return nil, nil
		}
	case Opcode(48):
		if uint64(index) < uint64(len(t.Field)) {
			return t.Field[index], nil
		}
	case Opcode(49):
		if uint64(index) < uint64(len(t.Type)) {
			return t.Type[index], nil
		}
	case Opcode(50):
		if uint64(index) < uint64(len(t.Type)) {
			return t.Type[index], nil
		}
	case Opcode(51):
		if uint64(index) < uint64(len(t.Type)) {
			return t.Type[index], nil
		}
	case Opcode(52):
		if uint64(index) < uint64(len(t.Address)) {
			return t.Address[index], nil
		}
	case Opcode(53):
		if index == 0 {
			return nil, nil
		}
	case Opcode(54):
		if index == 0 {
			return nil, nil
		}
	case Opcode(55):
		if index == 0 {
			return nil, nil
		}
	case Opcode(56):
		if index == 0 {
			return nil, nil
		}
	case Opcode(57):
		if index == 0 {
			return nil, nil
		}
	case Opcode(58):
		if index == 0 {
			return nil, nil
		}
	case Opcode(59):
		if index == 0 {
			return nil, nil
		}
	case Opcode(60):
		if index == 0 {
			return nil, nil
		}
	case Opcode(61):
		if index == 0 {
			return nil, nil
		}
	case Opcode(62):
		if index == 0 {
			return nil, nil
		}
	case Opcode(63):
		if uint64(index) < uint64(len(t.InitModule)) {
			return t.InitModule[index], nil
		}
	case Opcode(64):
		if uint64(index) < uint64(len(t.Export)) {
			return t.Export[index], nil
		}
	case Opcode(65):
		if uint64(index) < uint64(len(t.Call)) {
			return t.Call[index], nil
		}
	case Opcode(66):
		if uint64(index) < uint64(len(t.CallFFI)) {
			return t.CallFFI[index], nil
		}
	case Opcode(67):
		if uint64(index) < uint64(len(t.CallIntrinsic)) {
			return t.CallIntrinsic[index], nil
		}
	case Opcode(68):
		if uint64(index) < uint64(len(t.CompareBranch)) {
			return t.CompareBranch[index], nil
		}
	case Opcode(69):
		if uint64(index) < uint64(len(t.FieldPath)) {
			return t.FieldPath[index], nil
		}
	}
	return nil, fmt.Errorf("invalid descriptor %d for opcode %s", index, op)
}
func (t *DescriptorTables) Clone() DescriptorTables {
	out := DescriptorTables{}
	if t.Const != nil {
		out.Const = make([]ConstPayload, len(t.Const))
		for i, v := range t.Const {
			out.Const[i] = clonePayload(v).(ConstPayload)
		}
	}
	if t.Local != nil {
		out.Local = make([]LocalPayload, len(t.Local))
		for i, v := range t.Local {
			out.Local[i] = clonePayload(v).(LocalPayload)
		}
	}
	if t.Upvalue != nil {
		out.Upvalue = make([]UpvaluePayload, len(t.Upvalue))
		for i, v := range t.Upvalue {
			out.Upvalue[i] = clonePayload(v).(UpvaluePayload)
		}
	}
	if t.Global != nil {
		out.Global = make([]GlobalPayload, len(t.Global))
		for i, v := range t.Global {
			out.Global[i] = clonePayload(v).(GlobalPayload)
		}
	}
	if t.Address != nil {
		out.Address = make([]AddressPayload, len(t.Address))
		for i, v := range t.Address {
			out.Address[i] = clonePayload(v).(AddressPayload)
		}
	}
	if t.Type != nil {
		out.Type = make([]TypePayload, len(t.Type))
		for i, v := range t.Type {
			out.Type[i] = clonePayload(v).(TypePayload)
		}
	}
	if t.Operator != nil {
		out.Operator = make([]OperatorPayload, len(t.Operator))
		for i, v := range t.Operator {
			out.Operator[i] = clonePayload(v).(OperatorPayload)
		}
	}
	if t.MakeSequence != nil {
		out.MakeSequence = make([]MakeSequencePayload, len(t.MakeSequence))
		for i, v := range t.MakeSequence {
			out.MakeSequence[i] = clonePayload(v).(MakeSequencePayload)
		}
	}
	if t.MakeMap != nil {
		out.MakeMap = make([]MakeMapPayload, len(t.MakeMap))
		for i, v := range t.MakeMap {
			out.MakeMap[i] = clonePayload(v).(MakeMapPayload)
		}
	}
	if t.MakeStruct != nil {
		out.MakeStruct = make([]MakeStructPayload, len(t.MakeStruct))
		for i, v := range t.MakeStruct {
			out.MakeStruct[i] = clonePayload(v).(MakeStructPayload)
		}
	}
	if t.MakeSlice != nil {
		out.MakeSlice = make([]MakeSlicePayload, len(t.MakeSlice))
		for i, v := range t.MakeSlice {
			out.MakeSlice[i] = clonePayload(v).(MakeSlicePayload)
		}
	}
	if t.MakeWaitable != nil {
		out.MakeWaitable = make([]MakeWaitablePayload, len(t.MakeWaitable))
		for i, v := range t.MakeWaitable {
			out.MakeWaitable[i] = clonePayload(v).(MakeWaitablePayload)
		}
	}
	if t.Select != nil {
		out.Select = make([]SelectPayload, len(t.Select))
		for i, v := range t.Select {
			out.Select[i] = clonePayload(v).(SelectPayload)
		}
	}
	if t.Count != nil {
		out.Count = make([]CountPayload, len(t.Count))
		for i, v := range t.Count {
			out.Count[i] = clonePayload(v).(CountPayload)
		}
	}
	if t.Field != nil {
		out.Field = make([]FieldPayload, len(t.Field))
		for i, v := range t.Field {
			out.Field[i] = clonePayload(v).(FieldPayload)
		}
	}
	if t.Export != nil {
		out.Export = make([]ExportPayload, len(t.Export))
		for i, v := range t.Export {
			out.Export[i] = clonePayload(v).(ExportPayload)
		}
	}
	if t.InitModule != nil {
		out.InitModule = make([]InitModulePayload, len(t.InitModule))
		for i, v := range t.InitModule {
			out.InitModule[i] = clonePayload(v).(InitModulePayload)
		}
	}
	if t.Label != nil {
		out.Label = make([]LabelPayload, len(t.Label))
		for i, v := range t.Label {
			out.Label[i] = clonePayload(v).(LabelPayload)
		}
	}
	if t.Jump != nil {
		out.Jump = make([]JumpPayload, len(t.Jump))
		for i, v := range t.Jump {
			out.Jump[i] = clonePayload(v).(JumpPayload)
		}
	}
	if t.Call != nil {
		out.Call = make([]CallPayload, len(t.Call))
		for i, v := range t.Call {
			out.Call[i] = clonePayload(v).(CallPayload)
		}
	}
	if t.CallInterface != nil {
		out.CallInterface = make([]CallInterfacePayload, len(t.CallInterface))
		for i, v := range t.CallInterface {
			out.CallInterface[i] = clonePayload(v).(CallInterfacePayload)
		}
	}
	if t.Closure != nil {
		out.Closure = make([]ClosurePayload, len(t.Closure))
		for i, v := range t.Closure {
			out.Closure[i] = clonePayload(v).(ClosurePayload)
		}
	}
	if t.Return != nil {
		out.Return = make([]ReturnPayload, len(t.Return))
		for i, v := range t.Return {
			out.Return[i] = clonePayload(v).(ReturnPayload)
		}
	}
	if t.Defer != nil {
		out.Defer = make([]DeferPayload, len(t.Defer))
		for i, v := range t.Defer {
			out.Defer[i] = clonePayload(v).(DeferPayload)
		}
	}
	if t.CallFFI != nil {
		out.CallFFI = make([]CallFFIPayload, len(t.CallFFI))
		for i, v := range t.CallFFI {
			out.CallFFI[i] = clonePayload(v).(CallFFIPayload)
		}
	}
	if t.CallIntrinsic != nil {
		out.CallIntrinsic = make([]CallIntrinsicPayload, len(t.CallIntrinsic))
		for i, v := range t.CallIntrinsic {
			out.CallIntrinsic[i] = clonePayload(v).(CallIntrinsicPayload)
		}
	}
	if t.TypeDispatch != nil {
		out.TypeDispatch = make([]TypeDispatchPayload, len(t.TypeDispatch))
		for i, v := range t.TypeDispatch {
			out.TypeDispatch[i] = clonePayload(v).(TypeDispatchPayload)
		}
	}
	if t.CompareBranch != nil {
		out.CompareBranch = make([]CompareBranchPayload, len(t.CompareBranch))
		for i, v := range t.CompareBranch {
			out.CompareBranch[i] = clonePayload(v).(CompareBranchPayload)
		}
	}
	if t.FieldPath != nil {
		out.FieldPath = make([]FieldPathPayload, len(t.FieldPath))
		for i, v := range t.FieldPath {
			out.FieldPath[i] = clonePayload(v).(FieldPathPayload)
		}
	}
	return out
}
func (t *DescriptorTables) Bytes() int {
	total := 0
	for _, v := range t.Const {
		total += v.descriptorBytes()
	}
	for _, v := range t.Local {
		total += v.descriptorBytes()
	}
	for _, v := range t.Upvalue {
		total += v.descriptorBytes()
	}
	for _, v := range t.Global {
		total += v.descriptorBytes()
	}
	for _, v := range t.Address {
		total += v.descriptorBytes()
	}
	for _, v := range t.Type {
		total += v.descriptorBytes()
	}
	for _, v := range t.Operator {
		total += v.descriptorBytes()
	}
	for _, v := range t.MakeSequence {
		total += v.descriptorBytes()
	}
	for _, v := range t.MakeMap {
		total += v.descriptorBytes()
	}
	for _, v := range t.MakeStruct {
		total += v.descriptorBytes()
	}
	for _, v := range t.MakeSlice {
		total += v.descriptorBytes()
	}
	for _, v := range t.MakeWaitable {
		total += v.descriptorBytes()
	}
	for _, v := range t.Select {
		total += v.descriptorBytes()
	}
	for _, v := range t.Count {
		total += v.descriptorBytes()
	}
	for _, v := range t.Field {
		total += v.descriptorBytes()
	}
	for _, v := range t.Export {
		total += v.descriptorBytes()
	}
	for _, v := range t.InitModule {
		total += v.descriptorBytes()
	}
	for _, v := range t.Label {
		total += v.descriptorBytes()
	}
	for _, v := range t.Jump {
		total += v.descriptorBytes()
	}
	for _, v := range t.Call {
		total += v.descriptorBytes()
	}
	for _, v := range t.CallInterface {
		total += v.descriptorBytes()
	}
	for _, v := range t.Closure {
		total += v.descriptorBytes()
	}
	for _, v := range t.Return {
		total += v.descriptorBytes()
	}
	for _, v := range t.Defer {
		total += v.descriptorBytes()
	}
	for _, v := range t.CallFFI {
		total += v.descriptorBytes()
	}
	for _, v := range t.CallIntrinsic {
		total += v.descriptorBytes()
	}
	for _, v := range t.TypeDispatch {
		total += v.descriptorBytes()
	}
	for _, v := range t.CompareBranch {
		total += v.descriptorBytes()
	}
	for _, v := range t.FieldPath {
		total += v.descriptorBytes()
	}
	return total
}
