// Code generated by mini-go compiler-identity; DO NOT EDIT.

package bytecode

// CompilerIdentity identifies the compiler and bytecode semantics used by caches.
const CompilerIdentity = "0b9eaab8bb4a16bb01477ea6d200d0862f9064d1ab127f6a054ab3168c6d6261"
