// Code generated by mini-go compiler-identity; DO NOT EDIT.

package bytecode

// CompilerIdentity identifies the compiler and bytecode semantics used by caches.
const CompilerIdentity = "eacf326170db67a1353183fd49639dd68bd4a844a8cab6d7b0f0c2f67a2bf5bf"
