// Code generated by mini-go-dev compiler-binary; DO NOT EDIT.
package bytecode

import (
	"github.com/d7z-team/mini-go/compiler/identity"
	compiler_types "github.com/d7z-team/mini-go/compiler/types"
)

// EncodeIdentityConstant writes the compiler identity schema fields.
func EncodeIdentityConstant(w *identity.Writer, value Constant) {
	if !w.EnterStructure() {
		return
	}
	w.String(string(value.ID))
	compiler_types.EncodeIdentityTypeRef(w, value.Type)
	w.JSON(value.Value)
	w.Bool(bool(value.Untyped))
	w.LeaveStructure()
}

// EncodeIdentityExport writes the compiler identity schema fields.
func EncodeIdentityExport(w *identity.Writer, value Export) {
	if !w.EnterStructure() {
		return
	}
	w.String(string(value.Name))
	w.String(string(value.Kind))
	w.String(string(value.ID))
	compiler_types.EncodeIdentityTypeRef(w, value.Type)
	w.Bool(bool(value.Untyped))
	w.LeaveStructure()
}

// EncodeIdentityRequirement writes the compiler identity schema fields.
func EncodeIdentityRequirement(w *identity.Writer, value Requirement) {
	if !w.EnterStructure() {
		return
	}
	w.String(string(value.Kind))
	w.String(string(value.ModulePath))
	w.String(string(value.Hash))
	w.Uint(uint64(len(value.Exports)))
	for i0 := range value.Exports {
		w.String(string(value.Exports[i0]))
	}
	w.LeaveStructure()
}

// EncodeIdentitySourceFile writes the compiler identity schema fields.
func EncodeIdentitySourceFile(w *identity.Writer, value SourceFile) {
	if !w.EnterStructure() {
		return
	}
	w.String(string(value.ID))
	w.String(string(value.Path))
	w.String(string(value.Hash))
	w.LeaveStructure()
}
