// Code generated by mini-go compiler-identity; DO NOT EDIT.

package bytecode

// CompilerIdentity identifies the compiler and bytecode semantics used by caches.
const CompilerIdentity = "a44f4b9a0c49d31129361fc56898789daa9e0c938b795edf8415adfa1a3b3f4c"
