package bytecode

const (
	RuntimeNodeBytes     = 128
	RuntimeSlotBytes     = 16
	RuntimeMapEntryBytes = 32
	RuntimeByteBytes     = 1
)

var payloadSpecs = []PayloadSpec{
	{Name: "field_path", Fields: []FieldSpec{{Name: "type", Type: "TypeRef", Required: true}, {Name: "fields", Type: "[]uint32", Required: true}}},
	{Name: "compare_branch", Fields: []FieldSpec{{Name: "operator", Type: "comparison", Required: true}, {Name: "type", Type: "TypeRef", Required: true}, {Name: "label", Type: "label", Required: true}, {Name: "when", Type: "bool", Required: true}}},
	{Name: "type_dispatch", Fields: []FieldSpec{{Name: "subject", Type: "local-id", Required: true}, {Name: "default", Type: "label", Required: true}, {Name: "default_local", Type: "local-id"}, {Name: "cases", Type: "[]type-case", Required: true}}},
	{Name: "select", Fields: []FieldSpec{{Name: "index", Type: "local-id", Required: true}, {Name: "default", Type: "bool"}, {Name: "cases", Type: "[]select-case", Rule: "evaluated channel local and either send local or receive value/ok locals"}}},
	{Name: "const", Fields: []FieldSpec{{Name: "constant", Type: "constant-id", Required: true}}},
	{Name: "local", Fields: []FieldSpec{{Name: "local", Type: "local-id", Required: true}, {Name: "rebind", Type: "bool", Rule: "store_local only: replace the runtime local before a declaration binding is stored"}}},
	{Name: "upvalue", Fields: []FieldSpec{{Name: "upvalue", Type: "upvalue-id", Required: true}}},
	{Name: "global", Fields: []FieldSpec{{Name: "global", Type: "global-id", Required: true}}},
	{Name: "address", Fields: []FieldSpec{{Name: "kind", Type: "enum(local,upvalue,global,export)", Required: true}, {Name: "local", Type: "local-id"}, {Name: "upvalue", Type: "upvalue-id"}, {Name: "global", Type: "global-id"}, {Name: "module_path", Type: "module-path", Rule: "required for export addresses; mutually exclusive with local, upvalue and global ids"}, {Name: "export", Type: "export-name", Rule: "required for export addresses; must resolve to a global variable"}, {Name: "path", Type: "[]address-segment(field,index,indirect)"}}},
	{Name: "type", Fields: []FieldSpec{{Name: "type", Type: "canonical-type", Required: true}, {Name: "variadic", Type: "bool", Rule: "when true, type must be a function signature with a final Slice<T> parameter"}}},
	{Name: "operator", Fields: []FieldSpec{{Name: "operator", Type: "string", Required: true}}},
	{Name: "make_sequence", Fields: []FieldSpec{{Name: "type", Type: "canonical-type", Required: true}, {Name: "element_count", Type: "int", Required: true, Rule: "non-negative"}}},
	{Name: "make_map", Fields: []FieldSpec{{Name: "type", Type: "canonical-type", Required: true}, {Name: "entry_count", Type: "int", Required: true, Rule: "non-negative key/value pair count"}, {Name: "has_capacity", Type: "bool", Rule: "when true, the final input is a capacity hint after the key/value pairs"}}},
	{Name: "make_struct", Fields: []FieldSpec{{Name: "type", Type: "canonical-type", Required: true}, {Name: "fields", Type: "[]field-name"}}},
	{Name: "make_slice", Fields: []FieldSpec{{Name: "type", Type: "canonical-type", Required: true}, {Name: "has_capacity", Type: "bool"}}},
	{Name: "make_waitable", Fields: []FieldSpec{{Name: "type", Type: "canonical-type", Required: true}}},
	{Name: "count", Fields: []FieldSpec{{Name: "count", Type: "int", Required: true, Rule: "non-negative"}, {Name: "expand", Type: "bool"}}},
	{Name: "field", Fields: []FieldSpec{{Name: "field", Type: "field-name", Required: true}}},
	{Name: "export", Fields: []FieldSpec{{Name: "module_path", Type: "module-path", Required: true}, {Name: "export", Type: "export-name", Required: true}}},
	{Name: "init_module", Fields: []FieldSpec{{Name: "module_path", Type: "module-path", Required: true}}},
	{Name: "label", Fields: []FieldSpec{{Name: "label", Type: "label", Required: true}}},
	{Name: "jump", Fields: []FieldSpec{{Name: "label", Type: "label", Required: true}, {Name: "negate", Type: "bool", Rule: "jump_if branches when condition differs from negate; defaults to false; ignored by unconditional jump"}}},
	{Name: "call", Fields: []FieldSpec{{Name: "module_path", Type: "module-path", Rule: "optional exact target module; omitted for the current module"}, {Name: "function", Type: "function-id"}, {Name: "arg_count", Type: "int", Required: true, Rule: "non-negative"}, {Name: "result_count", Type: "int", Rule: "non-negative"}}},
	{Name: "call_interface", Fields: []FieldSpec{{Name: "interface_type", Type: "canonical-type", Required: true}, {Name: "method", Type: "method-name", Required: true}, {Name: "arg_count", Type: "int", Required: true, Rule: "non-negative"}, {Name: "result_count", Type: "int", Rule: "non-negative"}}},
	{Name: "closure", Fields: []FieldSpec{{Name: "module_path", Type: "module-path", Rule: "optional exact target module; omitted for the current module"}, {Name: "function", Type: "function-id", Required: true}, {Name: "captures", Type: "[]address", Rule: "local, upvalue or global captures in the creating frame"}}},
	{Name: "return", Fields: []FieldSpec{{Name: "result_count", Type: "int", Required: true, Rule: "non-negative"}}},
	{Name: "defer", Fields: []FieldSpec{{Name: "owner_depth", Type: "int", Rule: "optional non-negative caller depth; omitted or zero registers on the current frame"}}},
	{Name: "call_ffi", Fields: []FieldSpec{{Name: "arg_count", Type: "int", Required: true, Rule: "exactly two: route and payload"}, {Name: "result_count", Type: "int", Required: true, Rule: "exactly three: payload, message, status"}}},
	{Name: "call_intrinsic", Fields: []FieldSpec{{Name: "id", Type: "intrinsic-id", Required: true}, {Name: "arg_count", Type: "int", Required: true, Rule: "non-negative"}, {Name: "result_count", Type: "int", Rule: "non-negative"}}},
}

var opcodeSpecs = []OpcodeSpec{
	{Op: "type_dispatch", Arity: OperandArity{Kind: "fixed", Inputs: 0, Outputs: 0}, Category: "control", Payload: "type_dispatch", Operands: "no temporary operands", Notes: "select the first matching type case and bind its local"},
	{Op: "select", Arity: OperandArity{Kind: "fixed", Inputs: 0, Outputs: 0}, Category: "waitable", Payload: "select", Operands: "no temporary operands", Notes: "commit exactly one communication, storing index and receive results in locals; may suspend"},
	{Op: "const", Arity: OperandArity{Kind: "fixed", Inputs: 0, Outputs: 1}, Category: "value", Payload: "const", Operands: "write constant"},
	{Op: "zero", Arity: OperandArity{Kind: "fixed", Inputs: 0, Outputs: 1}, Category: "value", Payload: "type", Operands: "write zero value"},
	{Op: "pop", Arity: OperandArity{Kind: "fixed", Inputs: 1, Outputs: 0}, Category: "value", Operands: "read 1"},
	{Op: "unary", Arity: OperandArity{Kind: "fixed", Inputs: 1, Outputs: 1}, Category: "value", Payload: "operator", Operands: "read 1, write 1"},
	{Op: "binary", Arity: OperandArity{Kind: "fixed", Inputs: 2, Outputs: 1}, Category: "value", Payload: "operator", Operands: "read 2, write 1"},
	{Op: "load_local", Arity: OperandArity{Kind: "fixed", Inputs: 0, Outputs: 1}, Category: "value", Payload: "local", Operands: "write local"},
	{Op: "store_local", Arity: OperandArity{Kind: "fixed", Inputs: 1, Outputs: 0}, Category: "value", Payload: "local", Operands: "read value"},
	{Op: "load_upvalue", Arity: OperandArity{Kind: "fixed", Inputs: 0, Outputs: 1}, Category: "value", Payload: "upvalue", Operands: "write upvalue"},
	{Op: "store_upvalue", Arity: OperandArity{Kind: "fixed", Inputs: 1, Outputs: 0}, Category: "value", Payload: "upvalue", Operands: "read value"},
	{Op: "load_global", Arity: OperandArity{Kind: "fixed", Inputs: 0, Outputs: 1}, Category: "value", Payload: "global", Operands: "write global"},
	{Op: "store_global", Arity: OperandArity{Kind: "fixed", Inputs: 1, Outputs: 0}, Category: "value", Payload: "global", Operands: "read value"},
	{Op: "label", Arity: OperandArity{Kind: "fixed", Inputs: 0, Outputs: 0}, Category: "control", Payload: "label", Operands: "no temporary operands"},
	{Op: "jump", Arity: OperandArity{Kind: "fixed", Inputs: 0, Outputs: 0}, Category: "control", Payload: "jump", Operands: "no temporary operands", Terminal: true},
	{Op: "jump_if", Arity: OperandArity{Kind: "fixed", Inputs: 1, Outputs: 0}, Category: "control", Payload: "jump", Operands: "read condition"},
	{Op: "return", Arity: OperandArity{Kind: "payload"}, Category: "control", Payload: "return", Operands: "read count", Terminal: true},
	{Op: "panic", Arity: OperandArity{Kind: "fixed", Inputs: 1, Outputs: 0}, Category: "control", Operands: "read panic value", Terminal: true},
	{Op: "recover", Arity: OperandArity{Kind: "fixed", Inputs: 0, Outputs: 1}, Category: "control", Operands: "write recovered panic value"},
	{Op: "defer_push", Arity: OperandArity{Kind: "fixed", Inputs: 1, Outputs: 0}, Category: "control", Payload: "defer", Operands: "read function", Notes: "owner_depth lets compiler-lowered helper frames register a deferred call on an enclosing source frame"},
	{Op: "call_value", Arity: OperandArity{Kind: "payload"}, Category: "call", Payload: "call", Operands: "read callee and args, write results"},
	{Op: "call_direct", Arity: OperandArity{Kind: "payload"}, Category: "call", Payload: "call", Operands: "read args, write results"},
	{Op: "tail_call_direct", Arity: OperandArity{Kind: "payload"}, Category: "call", Payload: "call", Operands: "read args and complete through target", Terminal: true},
	{Op: "call_interface", Arity: OperandArity{Kind: "payload"}, Category: "call", Payload: "call_interface", Operands: "read interface receiver and args, write results", Notes: "dynamic dispatch by canonical interface method metadata; not Go source selector syntax"},
	{Op: "make_closure", Arity: OperandArity{Kind: "fixed", Inputs: 0, Outputs: 1}, Category: "call", Payload: "closure", Operands: "write closure"},
	{Op: "make_sequence", Arity: OperandArity{Kind: "payload"}, Category: "composite", Payload: "make_sequence", Operands: "read elements, write sequence"},
	{Op: "make_map", Arity: OperandArity{Kind: "payload"}, Category: "composite", Payload: "make_map", Operands: "read key/value pairs, write map"},
	{Op: "make_struct", Arity: OperandArity{Kind: "payload"}, Category: "composite", Payload: "make_struct", Operands: "read fields, write struct"},
	{Op: "make_slice", Arity: OperandArity{Kind: "payload"}, Category: "composite", Payload: "make_slice", Operands: "read len[/cap], write slice"},
	{Op: "make_waitable", Arity: OperandArity{Kind: "fixed", Inputs: 1, Outputs: 1}, Category: "resource", Payload: "make_waitable", Operands: "read capacity, write waitable resource", Notes: "compiler-defined communication resource; backend provides the waitable protocol"},
	{Op: "load_index", Arity: OperandArity{Kind: "fixed", Inputs: 2, Outputs: 1}, Category: "composite", Operands: "read object and index, write value"},
	{Op: "load_index_ok", Arity: OperandArity{Kind: "fixed", Inputs: 2, Outputs: 2}, Category: "composite", Operands: "read map and key, write value and ok"},
	{Op: "string_rune_at", Arity: OperandArity{Kind: "fixed", Inputs: 2, Outputs: 1}, Category: "composite", Operands: "read string and index, write rune"},
	{Op: "string_next_rune_index", Arity: OperandArity{Kind: "fixed", Inputs: 2, Outputs: 1}, Category: "composite", Operands: "read string and index, write next index"},
	{Op: "slice", Arity: OperandArity{Kind: "fixed", Inputs: 4, Outputs: 1}, Category: "composite", Operands: "read object/low/high/max, write slice"},
	{Op: "len", Arity: OperandArity{Kind: "fixed", Inputs: 1, Outputs: 1}, Category: "composite", Operands: "read object, write len"},
	{Op: "cap", Arity: OperandArity{Kind: "fixed", Inputs: 1, Outputs: 1}, Category: "composite", Operands: "read object, write cap"},
	{Op: "append", Arity: OperandArity{Kind: "payload"}, Category: "composite", Payload: "count", Operands: "read slice and values, write slice"},
	{Op: "delete", Arity: OperandArity{Kind: "fixed", Inputs: 2, Outputs: 0}, Category: "composite", Operands: "read map and key"},
	{Op: "clear", Arity: OperandArity{Kind: "fixed", Inputs: 1, Outputs: 0}, Category: "composite", Operands: "read container"},
	{Op: "copy", Arity: OperandArity{Kind: "fixed", Inputs: 2, Outputs: 1}, Category: "composite", Operands: "read dst/src, write copied count"},
	{Op: "map_keys", Arity: OperandArity{Kind: "fixed", Inputs: 1, Outputs: 1}, Category: "composite", Operands: "read map, write array of keys"},
	{Op: "map_iter_init", Arity: OperandArity{Kind: "fixed", Inputs: 1, Outputs: 0}, Category: "composite", Payload: "local", Operands: "read map; replace frame-owned iterator identified by local"},
	{Op: "map_iter_next", Arity: OperandArity{Kind: "fixed", Inputs: 0, Outputs: 3}, Category: "composite", Payload: "local", Operands: "write key, value, ok; skip deleted entries and observe current values"},
	{Op: "map_iter_close", Arity: OperandArity{Kind: "fixed", Inputs: 0, Outputs: 0}, Category: "composite", Payload: "local", Operands: "no temporary operands; release frame-owned iterator"},
	{Op: "load_field", Arity: OperandArity{Kind: "fixed", Inputs: 1, Outputs: 1}, Category: "composite", Payload: "field", Operands: "read object, write field"},
	{Op: "store_index", Arity: OperandArity{Kind: "fixed", Inputs: 3, Outputs: 0}, Category: "composite", Operands: "read object/index/value"},
	{Op: "store_field", Arity: OperandArity{Kind: "fixed", Inputs: 2, Outputs: 0}, Category: "composite", Payload: "field", Operands: "read object/value"},
	{Op: "type_assert", Arity: OperandArity{Kind: "fixed", Inputs: 1, Outputs: 1}, Category: "type_pointer", Payload: "type", Operands: "read value, write asserted value"},
	{Op: "type_assert_ok", Arity: OperandArity{Kind: "fixed", Inputs: 1, Outputs: 2}, Category: "type_pointer", Payload: "type", Operands: "read value, write value and ok"},
	{Op: "convert", Arity: OperandArity{Kind: "fixed", Inputs: 1, Outputs: 1}, Category: "type_pointer", Payload: "type", Operands: "read value, write converted value"},
	{Op: "address_of", Arity: OperandArity{Kind: "fixed", Inputs: 0, Outputs: 1}, Category: "type_pointer", Payload: "address", Operands: "write pointer", Notes: "export addresses initialize the target module through the scheduler and refer to its global slot"},
	{Op: "load_indirect", Arity: OperandArity{Kind: "fixed", Inputs: 1, Outputs: 1}, Category: "type_pointer", Operands: "read pointer, write value"},
	{Op: "store_indirect", Arity: OperandArity{Kind: "fixed", Inputs: 2, Outputs: 0}, Category: "type_pointer", Operands: "read pointer/value"},
	{Op: "waitable_send", Arity: OperandArity{Kind: "fixed", Inputs: 2, Outputs: 0}, Category: "waitable", Operands: "read waitable/value", Notes: "compiler-defined send capability; may block through the generic scheduler"},
	{Op: "waitable_recv", Arity: OperandArity{Kind: "fixed", Inputs: 1, Outputs: 1}, Category: "waitable", Operands: "read waitable, write value", Notes: "compiler-defined receive capability"},
	{Op: "waitable_recv_ok", Arity: OperandArity{Kind: "fixed", Inputs: 1, Outputs: 2}, Category: "waitable", Operands: "read waitable, write value/ok", Notes: "compiler-defined receive capability with completion state"},
	{Op: "waitable_can_recv", Arity: OperandArity{Kind: "fixed", Inputs: 1, Outputs: 1}, Category: "waitable", Operands: "read waitable, write ready", Notes: "receive readiness probe"},
	{Op: "waitable_try_recv", Arity: OperandArity{Kind: "fixed", Inputs: 1, Outputs: 2}, Category: "waitable", Operands: "read waitable, write value/ready", Notes: "non-blocking receive attempt"},
	{Op: "waitable_try_send", Arity: OperandArity{Kind: "fixed", Inputs: 2, Outputs: 1}, Category: "waitable", Operands: "read waitable/value, write ready", Notes: "non-blocking send attempt"},
	{Op: "waitable_can_send", Arity: OperandArity{Kind: "fixed", Inputs: 1, Outputs: 1}, Category: "waitable", Operands: "read waitable, write ready", Notes: "send readiness probe"},
	{Op: "waitable_close", Arity: OperandArity{Kind: "fixed", Inputs: 1, Outputs: 0}, Category: "waitable", Operands: "read waitable", Notes: "compiler-defined resource close operation"},
	{Op: "init_module", Arity: OperandArity{Kind: "fixed", Inputs: 0, Outputs: 0}, Category: "module", Payload: "init_module", Operands: "no temporary operands"},
	{Op: "load_export", Arity: OperandArity{Kind: "fixed", Inputs: 0, Outputs: 1}, Category: "module", Payload: "export", Operands: "write module export"},
	{Op: "spawn", Arity: OperandArity{Kind: "payload"}, Category: "scheduler", Payload: "call", Operands: "read callee and args"},
	{Op: "call_ffi", Arity: OperandArity{Kind: "payload"}, Category: "host", Payload: "call_ffi", Operands: "read route/payload, write payload/message/status", Notes: "opaque asynchronous host boundary; status: 0 success, 1 route unavailable, 2 failure"},
	{Op: "call_intrinsic", Arity: OperandArity{Kind: "payload"}, Category: "runtime", Payload: "call_intrinsic", Operands: "read args, write results"},
	{Op: "compare_branch", Arity: OperandArity{Kind: "fixed", Inputs: 2, Outputs: 0}, Category: "control", Payload: "compare_branch", Operands: "consume two operands", Notes: "compare typed operands and branch with explicit polarity"},
	{Op: "get_path", Arity: OperandArity{Kind: "fixed", Inputs: 1, Outputs: 1}, Category: "value", Payload: "field_path", Operands: "consume one operand, produce one result", Notes: "read a bounded sequence of declared fields"},
}

var knownOpcodes = func() map[string]Opcode {
	opcodes := make(map[string]Opcode, len(opcodeSpecs))
	for index, spec := range opcodeSpecs {
		opcodes[spec.Op] = Opcode(index + 1)
	}
	return opcodes
}()

var defaultValidationLimits = ValidationLimits{
	MaxTypes:               100000,
	MaxConstants:           100000,
	MaxGlobals:             100000,
	MaxFunctions:           100000,
	MaxExports:             100000,
	MaxRequirements:        10000,
	MaxInstructions:        10000000,
	MaxLocalsPerFunction:   100000,
	MaxUpvaluesPerFunction: 100000,
	MaxPayloadBytes:        67108864,
	MaxConstantBytes:       67108864,
}

var validationLimitSpecs = []FieldSpec{
	{Name: "MaxTypes", Type: "int", Rule: "maximum type declarations; non-positive disables this limit"},
	{Name: "MaxConstants", Type: "int", Rule: "maximum constants; non-positive disables this limit"},
	{Name: "MaxGlobals", Type: "int", Rule: "maximum globals; non-positive disables this limit"},
	{Name: "MaxFunctions", Type: "int", Rule: "maximum functions; non-positive disables this limit"},
	{Name: "MaxExports", Type: "int", Rule: "maximum exports; non-positive disables this limit"},
	{Name: "MaxRequirements", Type: "int", Rule: "maximum module requirements; non-positive disables this limit"},
	{Name: "MaxInstructions", Type: "int", Rule: "maximum total instructions; non-positive disables this limit"},
	{Name: "MaxLocalsPerFunction", Type: "int", Rule: "maximum locals per function; non-positive disables this limit"},
	{Name: "MaxUpvaluesPerFunction", Type: "int", Rule: "maximum upvalues per function; non-positive disables this limit"},
	{Name: "MaxPayloadBytes", Type: "int", Rule: "maximum single and aggregate logical descriptor bytes, including strings and tables; non-positive disables this limit"},
	{Name: "MaxConstantBytes", Type: "int", Rule: "maximum single constant bytes and total constant bytes; non-positive disables this limit"},
}
